ADMINS=${ADMINS}
ALLOWED_HOSTS=${ALLOWED_HOSTS}
SECRET_KEY=${SECRET_KEY}
DEBUG=${DEBUG}

ENV=${ENV}
HOST_GID=${HOST_GID}
HOST_UID=${HOST_UID}
WEB_PORT=${WEB_PORT}
DJANGO_PORT=${DJANGO_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
GUNICORN_WORKERS=${GUNICORN_WORKERS}
GUNICORN_THREADS=${GUNICORN_THREADS}
GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT}

DBF_SINAN=${DBF_SINAN}
IMPORTED_FILES_DIR=${IMPORTED_FILES_DIR}
TECHNICAL_REPORTS_ROOT=${TECHNICAL_REPORTS_ROOT}
SHAPEFILE_PATH=${SHAPEFILE_PATH}

DOCKER_HOST_SINAN_ROOT=${DOCKER_HOST_SINAN_ROOT}
DOCKER_HOST_IMPORTED_FILES_DIR=${DOCKER_HOST_SINAN_ROOT}/imported
DOCKER_HOST_INCOMING_DIR=${DOCKER_HOST_INCOMING_DIR}
DOCKER_HOST_TECHNICAL_REPORTS_DIR=${DOCKER_HOST_TECHNICAL_REPORTS_DIR}
DOCKER_HOST_LOG_DIR=${DOCKER_HOST_LOG_DIR}
DOCKER_HOST_MAPFILES_DIR=${DOCKER_HOST_MAPFILES_DIR}
DOCKER_HOST_SHAPEFILES_DIR=${DOCKER_HOST_SHAPEFILES_DIR}
DOCKER_HOST_TIFFS_DIR=${DOCKER_HOST_TIFFS_DIR}

EMAIL_BACKEND=${EMAIL_BACKEND}
EMAIL_CONFIG=${EMAIL_CONFIG}
EMAIL_CONNECTION_DEFAULT=${EMAIL_CONNECTION_DEFAULT}
EMAIL_FROM_USER=${EMAIL_FROM_USER}
EMAIL_HOST=${EMAIL_HOST}
EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
EMAIL_HOST_USER=${EMAIL_HOST_USER}
EMAIL_OUTLOOK_HOST=${EMAIL_OUTLOOK_HOST}
EMAIL_OUTLOOK_PASSWORD=${EMAIL_OUTLOOK_PASSWORD}
EMAIL_OUTLOOK_USER=${EMAIL_OUTLOOK_USER}
EMAIL_PORT=${EMAIL_PORT}
EMAIL_TO_ADDRESS=${EMAIL_TO_ADDRESS}

CELERY_BACKEND=${CELERY_BACKEND}
CELERY_BROKER_URL=${CELERY_BROKER_URL}
MEMCACHED_PORT=${MEMCACHED_PORT}
QUERY_CACHE_TIMEOUT=${QUERY_CACHE_TIMEOUT}
RABBITMQ_PORT=${RABBITMQ_PORT}

PORT_WEB=${PORT_WEB}
PSQL_DB=${PSQL_DB}
PSQL_DBF=${PSQL_DBF}
PSQL_HOST=${PSQL_HOST}
PSQL_PASSWORD=${PSQL_PASSWORD}
PSQL_PORT=${PSQL_PORT}
PSQL_USER=${PSQL_USER}
PSQL_DEV_USER=${PSQL_DEV_USER}
PSQL_DEV_PASSWORD=${PSQL_DEV_PASSWORD}
PG_RESTORE_STAGING=${PG_RESTORE_STAGING}
PG_DATA_STAGING=${PG_DATA_STAGING}
PG_DATA_DEV=${PG_DATA_DEV}
PG_DATA_PROD=${PG_DATA_PROD}

# MINIO
MINIO_UID=${MINIO_UID}
MINIO_GID=${MINIO_GID}
MINIO_PORT_1=${MINIO_PORT_1}
MINIO_PORT_2=${MINIO_PORT_2}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}

# EPISCANNER
EPISCANNER_PSQL_URI=${EPISCANNER_PSQL_URI}
EPISCANNER_HOST_DIR=${EPISCANNER_HOST_DIR}

# Sentry
SENTRY_DSN="${SENTRY_DSN}"

# CSRF Protection
CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE}
SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE}
