version: 1.0.0
compose-app: docker-compose
service-groups:
  - name: dev
    project-name: infodengue-dev
    compose-path: containers/compose.yaml
    env-file: .env
    services:
      default: postgres,memcached,rabbitmq,web,worker
      list:
        - name: postgres
          health-check: true
        - name: web
          health-check: true
        - name: worker
          health-check: true
        - name: memcached
          health-check: true
        - name: rabbitmq
          health-check: true

  - name: prod
    project-name: infodengue-prod
    compose-path: containers/compose.yaml
    env-file: .env
    services:
      default: dengue_db,web,memcached,rabbitmq,worker
      list:
        - name: dengue_db
          health-check: true
        - name: web
          health-check: true
        - name: worker
          health-check: true
        - name: memcached
          health-check: true
        - name: rabbitmq
          health-check: true

  - name: minio
    project-name: infodengue-prod
    compose-path: containers/compose.yaml
    env-file: .env
    services:
      default: minio
      list:
        - name: minio
          health-check: true
