version: 1.0.0
compose-app: docker-compose
env-file: .env
defaults:
  group: {{ env.ENV }}

service-groups:
  - name: dev
    project-name: infodengue-dev
    compose-path:
      - containers/compose.yaml
    env-file: .env
    services:
      default: memcached,rabbitmq,web,worker
      available:
        # - name: stagingdb
        - name: web
        - name: memcached
        - name: rabbitmq
        - name: worker

  - name: prod
    project-name: infodengue-prod
    compose-path: containers/compose.yaml
    env-file: .env
    services:
      default: memcached,rabbitmq,web,worker
      available:
        - name: postgres
        - name: web
        - name: memcached
        - name: rabbitmq
        - name: worker
