backend: bash
env-file: .envs/.env
groups:

  clean:
    tasks:
      tmp:
        help: remove build artifacts, compiled files, and cache
        backend: bash
        run: |
          find . -name '*.egg-info' -exec rm -rf {} +
          find . -name '*.egg' -exec rm -f {} +
          find . -name '*.pyc' -exec rm -f {} +
          find . -name '*.pyo' -exec rm -f {} +
          find . -name '__pycache__' -exec rm -rf {} +
          find . -name '*~' -exec rm -f {} +
          rm -rf build/
          rm -rf dist/
          rm -rf .eggs/
          rm -f .coverage
          rm -rf htmlcov/
          rm -rf .pytest_cache
          rm -rf .mypy_cache
          rm -rf .ruff_cache
          rm -rf .cache/
          find . -name "*.pyc" -delete
          echo "[II] Cleaned temporary files."
  # DJANGO
  django:
    env-file: .envs/.env
    help: Run Django commands and manage the development server.
    env:
      sugar_run_rm: sugar run --service web --options --rm
      manage_py: python manage.py
    tasks:
      # DEV MODE
      run:
        help: Start the development server locally.
        args:
          subcommand:
            help: Specify a Django subcommand to run.
            type: string
            default: runserver
        run: |
          cd AlertaDengue &&
          ${{ env.manage_py }} ${{ args.subcommand }}

      shell:
        help: Run the Django console interpreter inside the container.
        env-file: .envs/.env
        env:
          POSTGRES_HOST: localhost
          REDIS_HOST: localhost
        run: |
          sugar compose-ext start --services web -- -d
          python AlertaDengue/manage.py shell


      # CONTAINER
      collectstatic:
        help: Run the collectstatic for the backend service
        env-file: .envs/.env
        run: |
          CMD="python manage.py collectstatic --no-input"

          sugar --profile ${ENV} compose-ext start \
            --services postgres -- -d

          CMD="python manage.py collectstatic --no-input"
          sugar --profile ${{ env.ENV }}  compose-ext exec --service web --cmd "$CMD"
          echo "[II] postgres is running."

      static-geofiles:
        help: Generate geojson files and save them in the staticfiles folder.
        run: |
          ${{ env.sugar_run_rm }} --entrypoint "/opt/entrypoint.sh" --cmd ${{ env.manage_py }} sync_geofiles

      makemigrations:
        help: Run django makemigrations command (just for development)
        args:
          check:
            help: |
              Just check if the latest migration files were already created.
            type: bool
            action: store_true
        env-file: .envs/.env
        run: |
          sugar compose-ext start \
            --services postgres -- -d

          CWD=$(pwd)
          CMD_FLAG="${{ '--check' if args.check else '' }} --no-input"

          for app in 'dbf'; do
            echo -e "\nMaking migration files for: '${app}' ...\n"

            CMD="python manage.py makemigrations ${CMD_FLAG} ${app}"

            sugar --profile dev compose-ext run --rm --service web \
              --cmd "$CMD"

            echo "[II] postgres is running."


          done

          echo "[II] postgres is running."

      migrate:
        help: Migrate regarding to the current migration files
        env-file: .envs/.env
        run: |
          sugar compose-ext start \
            --services postgres -- -d

          CMD="python manage.py migrate --no-input"
          sugar --profile dev compose-ext run --rm --service web \
           --cmd "$CMD"

          echo "[II] postgres is running."


      send-mail-partner:
        help: Send email to partners.
        run: |
          ${{ env.sugar_run_rm }} --cmd ${{ env.manage_py }} send_mail

  # TESTS
  tests:
    help: Test tasks (dbdata TDD slice)
    env-file: .envs/.env
    tasks:
      setup:
        help: Setup infra for tests
        run: |
          sugar --profile dev compose-ext start --services postgres --options -d
          makim develop.container-wait --service postgres --timeout 90

      teardown:
        help: Teardown infra for tests
        run: |
          sugar --profile dev compose-ext stop

      lint:
        help: Run linter tools
        hooks:
          pre-run:
            - task: clean.tmp
        run: |
          pre-commit install
          pre-commit run --all-files --verbose

      typecheck:
        help: Run mypy (best-effort, skip third-party imports)
        run: |
          mypy --follow-imports=skip --ignore-missing-imports \
            AlertaDengue/dados/dbdata.py

      unit:
        help: Run tests with pytest (inside web container)
        args:
          path:
            help: Path or module to run (e.g., tests/dbdata)
            type: string
            default: "tests/dbdata"
          settings:
            help: Django settings module
            type: string
            default: "ad_main.settings.testing"
          params:
            help: Additional pytest params
            type: string
            default: "-vv"
        env-file: .envs/.env
        env:
          POSTGRES_HOST: localhost
          REDIS_HOST: localhost
        hooks:
          pre-run:
            - task: tests.setup
          post-run:
            - task: tests.teardown
        run: |
          CMD="PYTHONPATH=/opt/services/AlertaDengue \
            DJANGO_SETTINGS_MODULE=${{ args.settings }} \
            PGOPTIONS='-c search_path=test_views,public' \
            pytest -q ${{ args.path }} ${{ args.params }}"
          sugar --profile dev compose-ext run --rm --service web \
            --cmd "sh -lc \"$CMD\""

  develop:
    env-file: .envs/.env
    help: Development tasks and utilities.
    env:
      manage_py: python AlertaDengue/manage.py
    tasks:
      # CI
      container-wait:
        help: Wait for a specific service to become available.
        args:
          timeout:
            help: Define the timeout in seconds for the health check.
            type: string
            default: "30"
          service:
            help: Specify the name of the service to wait for.
            type: string
            required: true
        run: |
          timeout ${{ args.timeout }} ./containers/scripts/healthcheck.sh ${{ args.service }}

      container-wait-all:
        env-file: .envs/.env
        help: Wait until container is healthy
        args:
          timeout:
            help: the time (in seconds) for waiting the service
            type: string
            default: "90"
            required: false
        hooks:
          pre-run:
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: postgres
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: memcached
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: rabbitmq
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: web
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: celery

      clean:
        help: Clean all generated artifacts from the project.
        hooks:
          pre-run:
            - task: develop.clear_cache
        args:
          path:
            help: Specify the path of the files to remove.
            type: string
            default: ""
        run: |
          import shutil
          from pathlib import Path
          base_dir = Path(".")
          list_to_cache_files = [
            'build/', 'dist/', '.eggs/', '*/.eggs', 'db',
            '*.egg-info', '*.egg', '*.pyc', '*.pyo', '*~',
            '__pycache__', '*.ipynb_checkpoints', '*.pytest_cache'
          ]
          for item in list_to_cache_files:
            for file in base_dir.glob(f'**/{item}'):
              shutil.rmtree(file) if file.is_dir() else file.unlink()
      clear_cache:
        help: Clear all Django cache
        args:
          subcommand:
            help: Specify a Django subcommand to run.
            type: string
            default: clearcache
        run: |
          ${{ env.manage_py }} ${{ args.subcommand }}

  release:
    vars:
      app: |
        npx --yes \
          -p semantic-release \
          -p conventional-changelog-conventionalcommits \
          -p "@semantic-release/commit-analyzer" \
          -p "@semantic-release/release-notes-generator" \
          -p "@semantic-release/changelog" \
          -p "@semantic-release/exec" \
          -p "@semantic-release/github" \
          -p "@semantic-release/git" \
          -p "semantic-release-replace-plugin@1.2.7" \
          semantic-release

    tasks:
      ci:
        help: run semantic release on CI
        run: ${{ vars.app }} --ci

      dry:
        help: run semantic release in dry-run mode
        run: |
          ${{ vars.app }} --dry-run
