version: 1.0.0
env-file: .env
groups:
  default:
    env-file: .env
    vars:
      py_v: python --version
      sugar_build: containers-sugar build --group $ENV
      sugar_start: containers-sugar start --group $ENV
      sugar_down: containers-sugar stop --group $ENV
      sugar_exec: containers-sugar exec --group $ENV --services
      sugar_run: containers-sugar run --group $ENV --services web
      sugar_run_rm: containers-sugar run --group $ENV --services web --extras=--rm
      manage_py: python manage.py

    targets:

      # DEVELOPMENT
      runserver:
        help: Run Django server on localhost
        run: |
          cd AlertaDengue/ \
          && {{ manage_py }} runserver

      container-build:
        help: Build containers
        run: |
          {{ sugar_build }}

      container-start:
        help: Start all containers
        run: |
          {{ sugar_start }}

      container-exec:
        help:
        run: |
          {{ sugar_exec }} {{ args.service }}

      container-stop:
        help: Start all containers
        run: |
          {{ sugar_down }}


      # DJANGO
      static-geofiles:
        help: Generate static geofiles
        run: |
          {{ sugar_run_rm }} --cmd "{{ manage_py }} sync_geofiles"
          {{ sugar_run_rm }} --cmd "{{ manage_py }} collectstatic --noinput"
          # {{ sugar_run_rm }} --cmd "which python"

      django-migrate:
        dependencies:
          - target: containers.static-geofiles
        run: |
          for cmd in [
            "runserver",
            "migrate --database=dados --noinput",
            "migrate --database=infodengue --noinput",
            "migrate forecast --database=forecast"
          ]:
            {{ sugar_run }} --extras="{{extras}}" --cmd "{{ manage_py }} @(cmd)"

      send-mail-partner:
        run: |
          {{ sugar_run }} "{{ manage_py }} send_mail'


      # CI
      wait:
        help: Wait for a service
        args:
          timeout:
            help: Define the timeout for the healthcheck
            type: integer
            default: 30
          service:
            help: Service name that would be awaited
            type: string
            required: True

        run: |
          timeout {{ args.timeout }} ./containers/scripts/healthcheck.sh {{ args.service }}

      wait-all:
        run: |
          if $ENV == "dev":
            makim containers.wait --service "postgres"

          for service in ["postgres","memcached","rabbitmq","web","worker"]:
            makim containers.wait --service @(service)

      test-staging-web:
        run: |
          for test_name in ['dados', 'dbf', 'gis', 'api']:
            {{ sugar_run }} --extras '--no-deps' --cmd 'bash /opt/services/test.sh @(test_name)'

      test-staging-all:
        run: |
          {{ sugar_run_rm }} --cmd '{{manage_py}} test'


      # EPISCANNER
      update_episcanner:
        help: Create parquet files for episcanner
        run: |
          from epi_scanner.settings import STATES
          from epi_scanner.management import fetch_data
          for state in STATES:
              fetch_data.data_to_parquet(state)


      # DATABASE 
      grant-role:
        help: Grant read-only access to the database
        args:
          service:
            help: Database service name to modify access permissions
            type: string
            required: False
          command:
            help: Script or command to be executed inside the container
            type: string
            required: False
        run: |
          {{ sugar_exec }} {{ args.service }} --cmd "{{ args.command }}"


      # PYTHON
      clean:
        help: Clean all artifacts
        run: |
          for _path in ['build/', 'dist/', '.eggs/', '*/.eggs', 'db']:
            rm -fr @(_path)

          for _path in [
            '*.egg-info', '*.egg', '*.pyc', '*.pyo',
            '*~', '__pycache__', '*.ipynb_checkpoints', '*.pytest_cache'
          ]:
            find . -name '@(_path)' -exec rm -fr {} +
