env-file: .env
groups:

  # DJANGO
  django:
    env-file: .env
    help: Run Django commands and manage the development server.
    env:
      sugar_run_rm: sugar run --service web --options --rm
      manage_py: python manage.py
    tasks:
      # DEV MODE
      run:
        help: Start the development server locally.
        args:
          subcommand:
            help: Specify a Django subcommand to run.
            type: string
            default: runserver
        run: |
          cd AlertaDengue &&
          ${{ env.manage_py }} ${{ args.subcommand }}

      # CONTAINER
      static-collectstatic:
        help: Collect static files into a single location.
        run: |
          ${{ env.sugar_run_rm }} --entrypoint "/entrypoint.sh" --cmd ${{ env.manage_py }} collectstatic --noinput

      static-geofiles:
        help: Generate geojson files and save them in the staticfiles folder.
        run: |
          ${{ env.sugar_run_rm }} --entrypoint "/entrypoint.sh" --cmd ${{ env.manage_py }} sync_geofiles

      migrate:
        help: Apply database migrations for specified databases.
        run: |
          for cmd in [
            "--database=dados",
            "--database=infodengue",
            # "--database=forecast"
          ]:
            ${{ env.sugar_run_rm }} --entrypoint "/entrypoint.sh" --cmd ${{ env.manage_py }} migrate --noinput @(cmd)

      send-mail-partner:
        help: Send email to partners.
        run: |
          ${{ env.sugar_run_rm }} --cmd ${{ env.manage_py }} send_mail

      # TESTS
      test-staging-web:
        help: Run specific tests for web staging.
        run: |
          for test_name in ['dados', 'dbf', 'gis', 'api']:
            ${{ env.sugar_run_rm }} --entrypoint "/entrypoint.sh" --cmd . /opt/services/test.sh @(test_name)

      test-staging-all:
        help: Run all tests for web staging.
        run: |
          ${{ env.sugar_run_rm }} --entrypoint "/entrypoint.sh" --cmd ${{ env.manage_py }} test --noinput

  develop:
    env-file: .env
    help: Development tasks and utilities.
    env:
      manage_py: python AlertaDengue/manage.py
    tasks:
      # CI
      container-wait:
        help: Wait for a specific service to become available.
        args:
          timeout:
            help: Define the timeout in seconds for the health check.
            type: string
            default: "30"
          service:
            help: Specify the name of the service to wait for.
            type: string
            required: true
        run: |
          timeout ${{ args.timeout }} ./containers/scripts/healthcheck.sh ${{ args.service }}

      container-wait-all:
        help: Wait until container is healthy
        args:
          timeout:
            help: the time (in seconds) for waiting the service
            type: string
            default: "90"
            required: false

        hooks:
          pre-run:
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: stagingdb
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: memcached
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: rabbitmq
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: web
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: worker

      clean:
        help: Clean all generated artifacts from the project.
        hooks:
          pre-run:
            - task: develop.clear_cache
        args:
          path:
            help: Specify the path of the files to remove.
            type: string
            default: ""
        run: |
          import shutil
          from pathlib import Path
          base_dir = Path(".")
          list_to_cache_files = [
            'build/', 'dist/', '.eggs/', '*/.eggs', 'db',
            '*.egg-info', '*.egg', '*.pyc', '*.pyo', '*~',
            '__pycache__', '*.ipynb_checkpoints', '*.pytest_cache'
          ]
          for item in list_to_cache_files:
            for file in base_dir.glob(f'**/{item}'):
              shutil.rmtree(file) if file.is_dir() else file.unlink()
      clear_cache:
        help: Clear all Django cache
        args:
          subcommand:
            help: Specify a Django subcommand to run.
            type: string
            default: clearcache
        run: |
          ${{ env.manage_py }} ${{ args.subcommand }}

  release:
    vars:
      app: |
        npx --yes \
          -p semantic-release \
          -p conventional-changelog-conventionalcommits \
          -p "@semantic-release/commit-analyzer" \
          -p "@semantic-release/release-notes-generator" \
          -p "@semantic-release/changelog" \
          -p "@semantic-release/exec" \
          -p "@semantic-release/github" \
          -p "@semantic-release/git" \
          -p "semantic-release-replace-plugin@1.2.7" \
          semantic-release

    tasks:
      ci:
        help: run semantic release on CI
        run: ${{ vars.app }} --ci

      dry:
        help: run semantic release in dry-run mode
        run: |
          ${{ vars.app }} --dry-run
