version: 1.0.0
shell: bash
groups:
  - name: infodengue
    env-file: .env
    targets:
      clean:
        help: Use this target to clean up temporary files
        args:
          all:
            type: bool
            action: store-true
            help: Remove all files that are tracked by git
        run: |
          echo "remove file X"
      build:
        help: Build the program
        args:
          clean:
            type: bool
            action: store-true
        dependencies:
          - target: clean
            if: \${\{ args.clean == true \}\}
        run: |
          echo "Building service container..."
          containers-sugar build --group dev

      stop:
        help: Stop service container
        run: |
          echo "Stop service..."
          containers-sugar stop --group dev

      start:
        help: Starting service container
        run: |
          echo "Starting database..."
          containers-sugar start --group dev
