backend: bash
env-file: .envs/.env
groups:
  clean:
    tasks:
      tmp:
        help: remove build artifacts, compiled files, and cache
        backend: bash
        run: |
          find . -name '*.egg-info' -exec rm -rf {} +
          find . -name '*.egg' -exec rm -f {} +
          find . -name '*.pyc' -exec rm -f {} +
          find . -name '*.pyo' -exec rm -f {} +
          find . -name '__pycache__' -exec rm -rf {} +
          find . -name '*~' -exec rm -f {} +
          rm -rf build/
          rm -rf dist/
          rm -rf .eggs/
          rm -f .coverage
          rm -rf htmlcov/
          rm -rf .pytest_cache
          rm -rf .mypy_cache
          rm -rf .ruff_cache
          rm -rf .cache/
          find . -name "*.pyc" -delete
          echo "[II] Cleaned temporary files."

  django:
    env-file: .envs/.env
    help: Run Django commands and manage the development server.
    env:
      sugar_run_rm: sugar run --service web --options --rm
      manage_py: python manage.py
    tasks:
      runserver:
        help: Start the development server locally.
        env:
          REDIS_HOST: infodengue-dev-redis
          PSQL_HOST: infodengue-dev-postgres
          PSQL_PORT: "25432"
        run: |
          sugar compose-ext restart --options "-d"
          pushd ./AlertaDengue/
            python manage.py runserver 0.0.0.0:8000
          popd

      shell:
        help: Run the Django console interpreter inside the container.
        env-file: .envs/.env
        env:
          POSTGRES_HOST: localhost
          REDIS_HOST: localhost
        run: |
          sugar compose-ext restart --options "-d"
          pushd ./AlertaDengue/
            python manage.py shell
          popd

      collectstatic:
        help: Run the collectstatic for the backend service
        env-file: .envs/.env
        run: |
          CMD="python manage.py collectstatic --no-input"

          sugar --profile ${ENV} compose-ext start \
            --services postgres -- -d

          CMD="python manage.py collectstatic --no-input"
          sugar --profile ${{ env.ENV }}  compose-ext exec --service web --cmd "$CMD"


      static-geofiles:
        help: Generate geojson files and save them in the staticfiles folder.
        run: |
          ${{ env.sugar_run_rm }} --entrypoint "/opt/entrypoint.sh" --cmd ${{ env.manage_py }} sync_geofiles

      makemigrations:
        help: Run django makemigrations command (just for development)
        args:
          check:
            help: |
              Just check if the latest migration files were already created.
            type: bool
            action: store_true
        env-file: .envs/.env
        run: |
          sugar compose-ext start \
            --services postgres -- -d

          CWD=$(pwd)
          CMD_FLAG="${{ '--check' if args.check else '' }} --no-input"

          for app in 'dbf'; do
            echo -e "\nMaking migration files for: '${app}' ...\n"

            CMD="python manage.py makemigrations ${CMD_FLAG} ${app}"

            sugar --profile dev compose-ext run --rm --service web \
              --cmd "$CMD"

            echo "[II] postgres is running."
          done

          echo "[II] postgres is running."

      migrate:
        help: Migrate regarding to the current migration files
        env-file: .envs/.env
        run: |
          sugar compose-ext start \
            --services postgres -- -d

          CMD="python manage.py migrate --no-input"
          sugar --profile ${ENV} compose-ext run --rm --service web \
           --cmd "$CMD"

          echo "[II] postgres is running."

      send-mail-partner:
        help: Send email to partners.
        run: |
          ${{ env.sugar_run_rm }} --cmd ${{ env.manage_py }} send_mail

      clear_cache:
        help: Clear all Django cache
        args:
          subcommand:
            help: Specify a Django subcommand to run.
            type: string
            default: clearcache
        run: |
          ${{ env.manage_py }} ${{ args.subcommand }}

  develop:
    env-file: .envs/.env
    help: Development tasks and utilities.
    env:
      manage_py: python AlertaDengue/manage.py
    tasks:
      container-wait:
        help: Wait for a specific service to become available.
        args:
          timeout:
            help: Define the timeout in seconds for the health check.
            type: string
            default: "30"
          service:
            help: Specify the name of the service to wait for.
            type: string
            required: true
        run: |
          timeout ${{ args.timeout }} ./containers/scripts/healthcheck.sh ${{ args.service }}

      container-wait-all:
        env-file: .envs/.env
        help: Wait until container is healthy
        args:
          timeout:
            help: the time (in seconds) for waiting the service
            type: string
            default: "90"
            required: false
        hooks:
          pre-run:
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: postgres
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: memcached
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: rabbitmq
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: web
            - task: develop.container-wait
              args:
                timeout: ${{ args.timeout }}
                service: celery

  tests:
    tasks:
      setup:
        help: Setup the infrastructure for the tests
        env-file: .envs/.env
        env:
          POSTGRES_HOST: localhost
          REDIS_HOST: localhost
        run: |
          sugar --group dev compose-ext restart --options -d

      teardown:
        help: Teardown the infrastructure for the tests
        env-file: .envs/.env
        env:
          POSTGRES_HOST: localhost
          REDIS_HOST: localhost
        run: |
          sugar --group dev compose-ext stop

      lint:
        help: Run linter tools
        hooks:
          pre-run:
            - task: clean.tmp
        run: |
          pre-commit install
          pre-commit run --all-files --verbose

      staging-web:
        help: Run specific tests for web staging.
        run: |
          for test_name in ['dados', 'dbf', 'gis', 'api']:
            ${{ env.sugar_run_rm }} --entrypoint "/opt/entrypoint.sh" --cmd . /opt/services/test.sh @(test_name)

      staging-all:
        help: Run all tests for web staging.
        run: |
          ${{ env.sugar_run_rm }} --entrypoint "/opt/entrypoint.sh" --cmd ${{ env.manage_py }} test --noinput

  release:
    vars:
      app: |
        npx --yes \
          -p semantic-release \
          -p conventional-changelog-conventionalcommits \
          -p "@semantic-release/commit-analyzer" \
          -p "@semantic-release/release-notes-generator" \
          -p "@semantic-release/changelog" \
          -p "@semantic-release/exec" \
          -p "@semantic-release/github" \
          -p "@semantic-release/git" \
          -p "semantic-release-replace-plugin@1.2.7" \
          semantic-release

    tasks:
      ci:
        help: run semantic release on CI
        run: ${{ vars.app }} --ci

      dry:
        help: run semantic release in dry-run mode
        run: |
          ${{ vars.app }} --dry-run
