default_language_version:
  python: python3.10

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        files: ""
        exclude: ^$
        types: [python, file, python]
        stages: [commit]
        pass_filenames: true
        args: ["--line-length", "79"]

      - id: isort
        name: isort
        entry: isort
        language: python
        files: ""
        exclude: ^.*/js/.*$
        types: [python]
        stages: [commit]
        pass_filenames: true
        additional_dependencies: ["black"]
        args: ["--profile", "black", "-l", "79"]
