repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
     - id: flake8
       types:
         - python
       args: ['--config=./AlertaDengue/setup.cfg']
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
