backend: compose
env-file: .env
defaults:
  profile: ${{ env.ENV }}
  project-name: alertadengue${{ env.DOCKER_PROJECT_NAME }}

profiles:
  dev:
    project-name: infodengue-dev
    env-file: .env
    config-path:
      - containers/compose.yaml
      - containers/compose-dev.yaml
    services:
      default: 
        - memcached
        - rabbitmq
        - redis
        - web
        - worker
        - stagingdb
      available:
        - name: stagingdb
        - name: web
        - name: memcached
        - name: rabbitmq
        - name: redis
        - name: worker

  prod:
    project-name: infodengue-prod
    env-file: .env
    config-path:
      - containers/compose.yaml
      - containers/compose-dev.yaml
    services:
      default: 
        - memcached
        - rabbitmq
        - redis
        - web
        - worker
      available:
        - name: postgres
        - name: web
        - name: memcached
        - name: rabbitmq
        - name: redis
        - name: worker
