backend: compose
env-file: .envs/.env

defaults:
  profile: ${{ env.ENV }}
  project-name: infodengue-${{ env.ENV }}

profiles:
  dev:
    project-name: infodengue-dev
    env-file: .envs/.env
    config-path:
      - containers/compose-base.yaml
      - containers/compose-dev.yaml
    services:
      default:
        - postgres
        - memcached
        - rabbitmq
        - redis
        - web
        - celery
        - celery-beat
      available:
        - name: postgres
        - name: memcached
        - name: rabbitmq
        - name: redis
        - name: web
        - name: celery
        - name: celery-beat

  staging:
    project-name: infodengue-staging
    env-file: .envs/.env
    config-path:
      - containers/compose-base.yaml
      - containers/compose-staging.yaml
    services:
      default:
        - postgres
        - memcached
        - rabbitmq
        - redis
        - web
        - celery
        - celery-beat
      available:
        - name: postgres
        - name: memcached
        - name: rabbitmq
        - name: redis
        - name: web
        - name: celery
        - name: celery-beat

  prod:
    project-name: infodengue-prod
    env-file: .envs/.env
    config-path:
      - containers/compose-base.yaml
      - containers/compose-prod.yaml
    services:
      default:
        - postgres
        - memcached
        - rabbitmq
        - redis
        - web
        - celery
        - celery-beat
      available:
        - name: postgres
        - name: memcached
        - name: rabbitmq
        - name: redis
        - name: web
        - name: celery
        - name: celery-beat
