backend: compose
env-file: .env

defaults:
  profile: ${{ env.ENV }}
  project-name: infodengue-${{ env.ENV }}

profiles:
  dev:
    project-name: infodengue-dev
    env-file: .envs/.env.dev
    config-path:
      - containers/compose-base.yaml
      - containers/compose-dev.yaml
    services:
      default:
        - postgres
        - memcached
        - rabbitmq
        - redis
        - web
        - celery
      available:
        - name: postgres
        - name: memcached
        - name: rabbitmq
        - name: redis
        - name: web
        - name: celery

  staging:
    project-name: infodengue-staging
    env-file: .env.staging
    config-path:
      - containers/compose-base.yaml
      - containers/compose-staging.yaml
    services:
      default:
        - postgres
        - memcached
        - rabbitmq
        - redis
        - web
        - celery
      available:
        - name: postgres
        - name: memcached
        - name: rabbitmq
        - name: redis
        - name: web
        - name: celery

  prod:
    project-name: infodengue-prod
    env-file: .env.prod
    config-path:
      - containers/compose-base.yaml
      - containers/compose-prod.yaml
    services:
      default:
        - postgres
        - memcached
        - rabbitmq
        - redis
        - web
        - celery
      available:
        - name: postgres
        - name: memcached
        - name: rabbitmq
        - name: redis
        - name: web
        - name: celery
