version: 1.0.0
compose-app: docker-compose
env-file: .env
defaults:
  group: {{ env.ENV }}

groups:
  dev:
    project-name: infodengue-dev
    compose-path:
      - containers/compose.yaml
      - containers/compose-dev.yaml
    env-file: .env
    services:
      default: memcached,rabbitmq,redis,web,worker,stagingdb
      available:
        - name: stagingdb
        - name: web
        - name: memcached
        - name: rabbitmq
        - name: redis
        - name: worker

  prod:
    project-name: infodengue-prod
    compose-path: containers/compose.yaml
    env-file: .env
    services:
      default: memcached,rabbitmq,redis,web,worker
      available:
        - name: postgres
        - name: web
        - name: memcached
        - name: rabbitmq
        - name: redis
        - name: worker
