name: alertadengue-dev
channels:
  - conda-forge
dependencies:
  - beautifulsoup4  # needed by django-bootstrap4
  - celery
  - dbfread
  - dj-database-url
  - dj-static
  - django >=3.1.8,<4
  - django-bootstrap4
  - django-chunked-upload 1.1.3
  - django-leaflet
  - django-makemessages-xgettext
  - docker-compose
  - fastparquet
  - fiona
  - gdal >=2.4.2
  - geojson
  - geopandas
  - geopy
  - gunicorn
  - ibis-framework
  - make
  - numpy
  - pandas
  - pip==21.3
  - plotly 4.*
  - psycopg2
  - pyproj
  - python 3.8.*
  - python-dotenv
  - python-memcached
  - pytz
  - rasterio
  - sh
  - sqlalchemy
  # develop
  - black
  - flake8
  - ipython
  - jupyterlab
  - matplotlib
  - mock
  - mypy
  - pillow
  - pre-commit
  - pip:
    - django-maintenance-mode
    - django-pymemcache
    - simpledbf
    # develop
    - django-extensions
    - django-cprofile-middleware
