name: alertadengue
channels:
  - conda-forge
dependencies:
- celery
- dbfread
- dj-database-url
- dj-static
- django 3.*
- django-bootstrap4
- django-chunked-upload 1.1.3
- django-leaflet
- django-makemessages-xgettext
- docker-compose
- fiona
- gdal >=2.4.2
- geojson
- geopandas
- geopy
- gunicorn
- ibis-framework 1.4.*
- make
- numpy
- pandas <=1.1.5  # issue#385
- pip
- plotly 4.*
- psycopg2
- pyproj
- python 3.8.*
- python-dotenv
- python-memcached
- pytz
- rasterio
- sh
- sqlalchemy <1.4
# develop
- black
- flake8
- flake8
- ipython
- jupyterlab
- matplotlib
- mock
- mypy
- pillow
- pre-commit
- pip:
  - django-maintenance-mode
  # develop
  - django-extensions
