name: alertadengue
channels:
  - conda-forge
  - defaults
dependencies:
# production
- django
- django-bootstrap4
- django-leaflet
- geojson
- gunicorn
- numpy
- pandas
- pip
- python-decouple
- pytz
- psycopg2
- sqlalchemy
- python-memcached
- django-makemessages-xgettext
- mock
- dbfread
- dj-database-url
- django-chunked-upload
- docker-compose
- celery
- dj-static
- gdal
- fiona
- rasterio
- geopy
- geopandas
- sh
- ipython
- sqlparse
- plotly=4.0.0
# development
- jupyter
- black
- matplotlib
- pillow
- pre-commit
- flake8
- werkzeug
- pytest
- pytest-django
- pip:
  # development
  - jupyter_contrib_nbextensions
  - django-extensions
