name: alertadengue
channels:
  - conda-forge
  - defaults
dependencies:
- django
- django-bootstrap4
- django-leaflet
- boto3
- geojson
- gunicorn
- numpy
- pandas
- pip
- python-decouple
- pytz
- psycopg2
- sqlalchemy
- python-memcached
- django-makemessages-xgettext
- mock
- dbfread
- dj-database-url
- django-chunked-upload
- docker-compose
- celery
- dj-static
- pyproj=1.9.6
- gdal
- fiona
- rasterio
- geopy
- geopandas
- sh
- ipython
- sqlparse
- plotly=4.0.0
- pip:
  - BeautifulSoup4
