version: "2"
services:
    staging_memcache:
      image: memcached:latest
      hostname: staging_memcache
      ports: []
      restart: always

    staging_rabbitmq:
      image: rabbitmq:3
      hostname: staging_rabbitmq
      restart: always

    staging_db:
      image: postgres:9.5
      build:
        context: "."
        dockerfile: "Dockerfile-postgres"
      env_file:
        - .env
      hostname: staging_db
      volumes:
        - ${STAGING_DATA_DIR}:/var/lib/postgresql/data
      restart: always

    staging_web:
      build: .
      env_file:
        - .env
      ports:
        - 8001:8000
      environment:
        - MEMCACHED_HOST=staging_memcache
        - CELERY_BROKER_URL=amqp://guest:guest@staging_rabbitmq:5672
        - DATABASE_URL = postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@staging_db:5432/infodengue
        - PSQL_HOST=staging_db
      volumes:
        - ${DOCKER_HOST_MEDIA_ROOT}:/MEDIA_ROOT
      depends_on:
        - staging_db
        - staging_rabbitmq
        - staging_memcache
      restart: always

    staging_celery-worker:
      build:
        context: "."
        dockerfile: "Dockerfile-celery"
      env_file:
        - .env
      environment:
        - CELERY_BROKER_URL=amqp://guest:guest@staging_rabbitmq:5672
        - DATABASE_URL = postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@staging_db:5432/infodengue
        - PSQL_HOST=staging_db
      volumes:
        - ${DOCKER_HOST_MEDIA_ROOT}:/MEDIA_ROOT
        - ${DOCKER_HOST_IMPORTED_FILES_DIR}:/IMPORTED_FILES
      depends_on:
        - staging_db
        - staging_rabbitmq
        - staging_memcache
      restart: always
