#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKFLOW="${SCRIPT_DIR}/archive_schemas_workflow.sh"
REMOVE_SQL="${SCRIPT_DIR}/20260729_03_remove_archive_schemas.sql"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'missing required command: %s\n' "$1" >&2
    exit 1
  }
}

for cmd in awk cp createdb date dropdb grep mktemp psql realpath rm sha256sum sleep; do
  require_cmd "$cmd"
done

export PGHOST="${PGHOST:-127.0.0.1}"
export PGPORT="${PGPORT:-25432}"
export PGUSER="${PGUSER:-dengueadmin}"

OUTPUT_ROOT="${1:-}"
[[ -n "$OUTPUT_ROOT" ]] || {
  printf 'usage: %s <absolute-output-root-outside-git-and-pgdata>\n' "${0##*/}" >&2
  exit 1
}
mkdir -p "$OUTPUT_ROOT"
OUTPUT_ROOT="$(realpath "$OUTPUT_ROOT")"

tmp_dir="$(mktemp -d)"
declare -a DBS_TO_DROP=()

cleanup() {
  local db
  for db in "${DBS_TO_DROP[@]}"; do
    dropdb --if-exists "$db" >/dev/null 2>&1 || true
  done
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

psql_db() {
  local db="$1"
  shift
  PGDATABASE="$db" psql -X -v ON_ERROR_STOP=1 "$@"
}

add_db() {
  DBS_TO_DROP+=("$1")
}

make_db() {
  local db="$1"
  dropdb --if-exists "$db" >/dev/null 2>&1 || true
  createdb -T template0 "$db"
  add_db "$db"
}

assert_archive_count() {
  local db="$1"
  local expected="$2"
  local got
  got="$(PGDATABASE="$db" psql -X -At -v ON_ERROR_STOP=1 -c "SELECT count(*) FROM pg_namespace WHERE nspname ~ '^archive_'")"
  [[ "$got" == "$expected" ]] || {
    printf 'archive schema count mismatch for %s: expected %s got %s\n' "$db" "$expected" "$got" >&2
    exit 1
  }
}

create_synthetic_source() {
  local db="$1"
  psql_db "$db" <<'SQL'
CREATE SCHEMA "Dengue_global";
CREATE SCHEMA "Municipio";
CREATE SCHEMA weather;

CREATE TABLE "Dengue_global".regional (id integer PRIMARY KEY);
CREATE TABLE "Dengue_global"."CID10" (codigo character varying(4) PRIMARY KEY);
CREATE TABLE "Dengue_global".regional_saude (
  id integer PRIMARY KEY,
  municipio_geocodigo integer UNIQUE
);

CREATE TABLE "Municipio"."Notificacao" (id bigint PRIMARY KEY);
CREATE TABLE "Municipio"."Historico_alerta" (
  "data_iniSE" date,
  "SE" integer,
  casos_est real,
  casos_est_min integer,
  casos_est_max integer,
  casos integer,
  municipio_geocodigo integer
);
CREATE TABLE "Municipio"."Historico_alerta_chik" (
  "data_iniSE" date,
  "SE" integer,
  casos_est real,
  casos_est_min integer,
  casos_est_max integer,
  casos integer,
  municipio_geocodigo integer
);

CREATE TABLE weather.copernicus_bra (
  date date,
  geocode bigint
);

INSERT INTO "Dengue_global".regional VALUES (10), (20), (30);
INSERT INTO "Dengue_global"."CID10" VALUES ('A900'), ('A901');
INSERT INTO "Dengue_global".regional_saude VALUES (1, 3304557);
INSERT INTO "Municipio"."Notificacao" VALUES (1);
INSERT INTO weather.copernicus_bra VALUES ('2026-01-01', 3304557);
INSERT INTO "Municipio"."Historico_alerta" VALUES ('2026-01-04', 1, 1, 1, 1, 1, 3304557);
INSERT INTO "Municipio"."Historico_alerta_chik" VALUES ('2026-01-04', 1, 2, 2, 2, 2, 3304557);

CREATE SCHEMA archive_alertas_regionais;
CREATE TABLE archive_alertas_regionais.alerta_mrj (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, aps integer, se integer);
CREATE UNIQUE INDEX alerta_mrj_aps_se_idx ON archive_alertas_regionais.alerta_mrj (aps, se);
CREATE TABLE archive_alertas_regionais.alerta_mrj_chik (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, aps integer, se integer);
CREATE UNIQUE INDEX alerta_mrj_chik_aps_se_idx ON archive_alertas_regionais.alerta_mrj_chik (aps, se);
CREATE TABLE archive_alertas_regionais.alerta_mrj_zika (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, aps integer, se integer);
CREATE UNIQUE INDEX alerta_mrj_zika_aps_se_idx ON archive_alertas_regionais.alerta_mrj_zika (aps, se);
CREATE TABLE archive_alertas_regionais.alerta_regional_chik (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_regional integer NOT NULL,
  CONSTRAINT regional_fk FOREIGN KEY (id_regional) REFERENCES "Dengue_global".regional(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE archive_alertas_regionais.alerta_regional_dengue (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_regional integer NOT NULL,
  CONSTRAINT regional_fk FOREIGN KEY (id_regional) REFERENCES "Dengue_global".regional(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE archive_alertas_regionais.alerta_regional_zika (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_regional integer NOT NULL,
  CONSTRAINT regional_fk FOREIGN KEY (id_regional) REFERENCES "Dengue_global".regional(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);
INSERT INTO archive_alertas_regionais.alerta_mrj (aps, se) VALUES (1, 202601);
INSERT INTO archive_alertas_regionais.alerta_mrj_chik (aps, se) VALUES (1, 202601);
INSERT INTO archive_alertas_regionais.alerta_mrj_zika (aps, se) VALUES (1, 202601);
INSERT INTO archive_alertas_regionais.alerta_regional_chik (id_regional) VALUES (10);
INSERT INTO archive_alertas_regionais.alerta_regional_dengue (id_regional) VALUES (20);
INSERT INTO archive_alertas_regionais.alerta_regional_zika (id_regional) VALUES (30);

CREATE SCHEMA archive_cemaden;
CREATE TABLE archive_cemaden."Estacao_cemaden" (codestacao text PRIMARY KEY);
CREATE TABLE archive_cemaden."Clima_cemaden" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codestacao text REFERENCES archive_cemaden."Estacao_cemaden"(codestacao)
);
COMMENT ON TABLE archive_cemaden."Clima_cemaden" IS 'synthetic archive fixture';
INSERT INTO archive_cemaden."Estacao_cemaden" VALUES ('A1');
INSERT INTO archive_cemaden."Clima_cemaden" (codestacao) VALUES ('A1');

CREATE SCHEMA archive_copernicus;
CREATE TABLE archive_copernicus.copernicus_arg (date date, geocode bigint);
CREATE TABLE archive_copernicus.copernicus_foz_do_iguacu (index integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
INSERT INTO archive_copernicus.copernicus_arg VALUES ('2026-01-01', 3304557);
INSERT INTO archive_copernicus.copernicus_foz_do_iguacu DEFAULT VALUES;

CREATE SCHEMA archive_historico_casos;
CREATE MATERIALIZED VIEW archive_historico_casos.historico_casos AS
SELECT 'dengue'::text AS disease, "data_iniSE", "SE", municipio_geocodigo, casos
FROM "Municipio"."Historico_alerta"
UNION ALL
SELECT 'chik'::text AS disease, "data_iniSE", "SE", municipio_geocodigo, casos
FROM "Municipio"."Historico_alerta_chik";
CREATE INDEX archive_historico_casos_idx ON archive_historico_casos.historico_casos (municipio_geocodigo);

CREATE SCHEMA archive_mosqlimate;
CREATE TABLE archive_mosqlimate.sprint202425 (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payload text
);
INSERT INTO archive_mosqlimate.sprint202425 (payload) VALUES ('fixture');

CREATE SCHEMA archive_ovitrampa;
CREATE TABLE archive_ovitrampa."Localidade" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
CREATE TABLE archive_ovitrampa."Bairro" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Localidade_id" integer REFERENCES archive_ovitrampa."Localidade"(id)
);
CREATE TABLE archive_ovitrampa."Ovitrampa" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Localidade_id" integer REFERENCES archive_ovitrampa."Localidade"(id)
);
INSERT INTO archive_ovitrampa."Localidade" DEFAULT VALUES;
INSERT INTO archive_ovitrampa."Bairro" ("Localidade_id") VALUES (1);
INSERT INTO archive_ovitrampa."Ovitrampa" ("Localidade_id") VALUES (1);

CREATE SCHEMA archive_redemet;
CREATE TABLE archive_redemet.clima_wu (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE archive_redemet.estacao_wu (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE archive_redemet.localidade_station_codes (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE archive_redemet.manifest (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payload text);
CREATE TABLE archive_redemet.parameters_station_codes (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE archive_redemet.regional_saude_station_codes (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
INSERT INTO archive_redemet.manifest (payload) VALUES ('fixture');

CREATE SCHEMA archive_tweets;
CREATE TABLE archive_tweets."Tweet" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CID10_codigo" character varying(4) NOT NULL,
  "data" date,
  CONSTRAINT "Tweet_CID10" FOREIGN KEY ("CID10_codigo") REFERENCES "Dengue_global"."CID10"(codigo) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX "Tweets_idx_data" ON archive_tweets."Tweet" ("data");
INSERT INTO archive_tweets."Tweet" ("CID10_codigo", "data") VALUES ('A900', '2026-01-01');

CREATE SCHEMA archive_upload;
CREATE TABLE archive_upload.chunked_upload (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE archive_upload.manifest (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payload text);
CREATE TABLE archive_upload.sinan_chunked_upload (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE archive_upload.sinan_upload (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE archive_upload.sinan_upload_log_status (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
INSERT INTO archive_upload.manifest (payload) VALUES ('fixture');
SQL
}

parse_key() {
  local file="$1"
  local key="$2"
  awk -F= -v key="$key" '$1 == key {print $2}' "$file"
}

workflow_export() {
  local db="$1"
  local out="$2"
  PGDATABASE="$db" ARCHIVE_EXPORT_ROOT="$OUTPUT_ROOT" "$WORKFLOW" export --output-root "$OUTPUT_ROOT" > "$out"
}

workflow_verify() {
  local db="$1"
  local package="$2"
  local out="$3"
  PGDATABASE="$db" "$WORKFLOW" verify --package "$package" > "$out"
}

workflow_remove() {
  local db="$1"
  local package="$2"
  local out="$3"
  PGDATABASE="$db" "$WORKFLOW" remove --package "$package" --confirm-database "$db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS > "$out"
}

expect_fail() {
  local label="$1"
  shift
  if "$@" > "${tmp_dir}/${label}.out" 2> "${tmp_dir}/${label}.err"; then
    printf 'expected failure but command succeeded: %s\n' "$label" >&2
    exit 1
  fi
}

copy_package() {
  local source="$1"
  local target="$2"
  rm -rf "$target"
  cp -a "$source" "$target"
}

prepare_verified_package() {
  local db="$1"
  local tag="$2"
  local export_out="${tmp_dir}/${tag}_export.out"
  local verify_out="${tmp_dir}/${tag}_verify.out"
  workflow_export "$db" "$export_out"
  local package
  package="$(parse_key "$export_out" ARCHIVE_PACKAGE_PATH)"
  workflow_verify "$db" "$package" "$verify_out"
  printf '%s\n' "$package"
}

mutant_root="${OUTPUT_ROOT}/mutants"
mkdir -p "$mutant_root"

positive_db="archive_workflow_positive"
make_db "$positive_db"
create_synthetic_source "$positive_db"
positive_package="$(prepare_verified_package "$positive_db" positive)"
workflow_remove "$positive_db" "$positive_package" "${tmp_dir}/positive_remove.out"
assert_archive_count "$positive_db" 0
expect_fail second_removal env PGDATABASE="$positive_db" "$WORKFLOW" remove --package "$positive_package" --confirm-database "$positive_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS

raw_sql_db="archive_workflow_raw_sql"
make_db "$raw_sql_db"
create_synthetic_source "$raw_sql_db"
expect_fail direct_sql env PGDATABASE="$raw_sql_db" psql -X -v ON_ERROR_STOP=1 -f "$REMOVE_SQL"
grep -q 'Direct execution is not supported. Use archive_schemas_workflow.sh remove with a verified persistent package.' "${tmp_dir}/direct_sql.err"

package_db="archive_workflow_package"
make_db "$package_db"
create_synthetic_source "$package_db"
base_package="$(prepare_verified_package "$package_db" package)"

tmp_package="/tmp/archive_workflow_pkg_tmp"
rm -rf "$tmp_package"
cp -a "$base_package" "$tmp_package"
expect_fail tmp_path env PGDATABASE="$package_db" "$WORKFLOW" verify --package "$tmp_package"

git_package="${PWD}/.archive_workflow_pkg_git"
rm -rf "$git_package"
cp -a "$base_package" "$git_package"
expect_fail git_path env PGDATABASE="$package_db" "$WORKFLOW" verify --package "$git_package"
rm -rf "$git_package"

missing_dump_pkg="${mutant_root}/missing_dump"
copy_package "$base_package" "$missing_dump_pkg"
rm -f "${missing_dump_pkg}/dengue_archive_schemas.dump"
expect_fail missing_dump env PGDATABASE="$package_db" "$WORKFLOW" verify --package "$missing_dump_pkg"

empty_dump_pkg="${mutant_root}/empty_dump"
copy_package "$base_package" "$empty_dump_pkg"
: > "${empty_dump_pkg}/dengue_archive_schemas.dump"
expect_fail empty_dump env PGDATABASE="$package_db" "$WORKFLOW" verify --package "$empty_dump_pkg"

changed_dump_pkg="${mutant_root}/changed_dump"
copy_package "$base_package" "$changed_dump_pkg"
printf 'x' >> "${changed_dump_pkg}/dengue_archive_schemas.dump"
expect_fail changed_dump env PGDATABASE="$package_db" "$WORKFLOW" verify --package "$changed_dump_pkg"

changed_toc_pkg="${mutant_root}/changed_toc"
copy_package "$base_package" "$changed_toc_pkg"
printf '\nBROKEN_TOC\n' >> "${changed_toc_pkg}/dengue_archive_schemas.toc"
expect_fail changed_toc env PGDATABASE="$package_db" "$WORKFLOW" verify --package "$changed_toc_pkg"

missing_receipt_pkg="${mutant_root}/missing_receipt"
copy_package "$base_package" "$missing_receipt_pkg"
rm -f "${missing_receipt_pkg}/verification_receipt.tsv"
expect_fail missing_receipt env PGDATABASE="$package_db" "$WORKFLOW" remove --package "$missing_receipt_pkg" --confirm-database "$package_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS

changed_receipt_pkg="${mutant_root}/changed_receipt_checksum"
copy_package "$base_package" "$changed_receipt_pkg"
printf 'bad  verification_receipt.tsv\n' > "${changed_receipt_pkg}/verification_receipt.tsv.sha256"
expect_fail changed_receipt_checksum env PGDATABASE="$package_db" "$WORKFLOW" remove --package "$changed_receipt_pkg" --confirm-database "$package_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS

path_mismatch_pkg="${mutant_root}/path_mismatch"
copy_package "$base_package" "$path_mismatch_pkg"
expect_fail path_mismatch env PGDATABASE="$package_db" "$WORKFLOW" remove --package "$path_mismatch_pkg" --confirm-database "$package_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS

identity_db_a="archive_workflow_identity_a"
identity_db_b="archive_workflow_identity_b"
make_db "$identity_db_a"
make_db "$identity_db_b"
create_synthetic_source "$identity_db_a"
create_synthetic_source "$identity_db_b"
identity_package="$(prepare_verified_package "$identity_db_a" identity)"
expect_fail identity_mismatch env PGDATABASE="$identity_db_b" "$WORKFLOW" remove --package "$identity_package" --confirm-database "$identity_db_b" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS
assert_archive_count "$identity_db_b" 9

inventory_db="archive_workflow_inventory_drift"
make_db "$inventory_db"
create_synthetic_source "$inventory_db"
inventory_package="$(prepare_verified_package "$inventory_db" inventory)"
psql_db "$inventory_db" -c "COMMENT ON TABLE archive_upload.manifest IS 'inventory drift'"
expect_fail inventory_drift env PGDATABASE="$inventory_db" "$WORKFLOW" remove --package "$inventory_package" --confirm-database "$inventory_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS
assert_archive_count "$inventory_db" 9

rowcount_db="archive_workflow_rowcount_drift"
make_db "$rowcount_db"
create_synthetic_source "$rowcount_db"
rowcount_package="$(prepare_verified_package "$rowcount_db" rowcount)"
psql_db "$rowcount_db" -c "INSERT INTO archive_upload.manifest (payload) VALUES ('drift')"
expect_fail rowcount_drift env PGDATABASE="$rowcount_db" "$WORKFLOW" remove --package "$rowcount_package" --confirm-database "$rowcount_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS
assert_archive_count "$rowcount_db" 9

fk_db="archive_workflow_fk_drift"
make_db "$fk_db"
create_synthetic_source "$fk_db"
fk_package="$(prepare_verified_package "$fk_db" fk)"
psql_db "$fk_db" -c 'ALTER TABLE archive_tweets."Tweet" DROP CONSTRAINT "Tweet_CID10"'
psql_db "$fk_db" -c 'ALTER TABLE archive_tweets."Tweet" ADD CONSTRAINT "Tweet_CID10" FOREIGN KEY ("CID10_codigo") REFERENCES "Dengue_global"."CID10"(codigo) NOT VALID'
expect_fail external_fk_drift env PGDATABASE="$fk_db" "$WORKFLOW" remove --package "$fk_package" --confirm-database "$fk_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS
assert_archive_count "$fk_db" 9

dep_db="archive_workflow_dependency_drift"
make_db "$dep_db"
create_synthetic_source "$dep_db"
dep_package="$(prepare_verified_package "$dep_db" dependency)"
psql_db "$dep_db" -c "CREATE VIEW public.active_archive_probe AS SELECT id FROM archive_upload.manifest"
expect_fail active_to_archive_dependency env PGDATABASE="$dep_db" "$WORKFLOW" remove --package "$dep_package" --confirm-database "$dep_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS
assert_archive_count "$dep_db" 9

unexpected_db="archive_workflow_unexpected_schema"
make_db "$unexpected_db"
create_synthetic_source "$unexpected_db"
unexpected_package="$(prepare_verified_package "$unexpected_db" unexpected)"
psql_db "$unexpected_db" -c "CREATE SCHEMA archive_unexpected"
psql_db "$unexpected_db" -c "CREATE TABLE archive_unexpected.probe (id integer)"
expect_fail unexpected_archive_schema env PGDATABASE="$unexpected_db" "$WORKFLOW" remove --package "$unexpected_package" --confirm-database "$unexpected_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS

missing_schema_db="archive_workflow_missing_schema"
make_db "$missing_schema_db"
create_synthetic_source "$missing_schema_db"
missing_schema_package="$(prepare_verified_package "$missing_schema_db" missing_schema)"
psql_db "$missing_schema_db" -c 'DROP TABLE archive_upload.chunked_upload'
psql_db "$missing_schema_db" -c 'DROP TABLE archive_upload.manifest'
psql_db "$missing_schema_db" -c 'DROP TABLE archive_upload.sinan_chunked_upload'
psql_db "$missing_schema_db" -c 'DROP TABLE archive_upload.sinan_upload'
psql_db "$missing_schema_db" -c 'DROP TABLE archive_upload.sinan_upload_log_status'
psql_db "$missing_schema_db" -c 'DROP SCHEMA archive_upload'
expect_fail approved_archive_missing env PGDATABASE="$missing_schema_db" "$WORKFLOW" remove --package "$missing_schema_package" --confirm-database "$missing_schema_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS

protected_db="archive_workflow_protected_drift"
make_db "$protected_db"
create_synthetic_source "$protected_db"
protected_package="$(prepare_verified_package "$protected_db" protected)"
psql_db "$protected_db" -c "COMMENT ON TABLE weather.copernicus_bra IS 'protected drift'"
expect_fail protected_object_drift env PGDATABASE="$protected_db" "$WORKFLOW" remove --package "$protected_package" --confirm-database "$protected_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS
assert_archive_count "$protected_db" 9

lock_db="archive_workflow_lock"
make_db "$lock_db"
create_synthetic_source "$lock_db"
lock_package="$(prepare_verified_package "$lock_db" lock)"
psql_db "$lock_db" -c "BEGIN; LOCK TABLE archive_alertas_regionais.alerta_mrj IN SHARE MODE; SELECT pg_sleep(1800);" > /dev/null 2>&1 &
lock_pid=$!
lock_ready=0
for _ in $(seq 1 30); do
  if [[ "$(PGDATABASE="$lock_db" psql -X -At -v ON_ERROR_STOP=1 -c "SELECT count(*) FROM pg_locks AS l JOIN pg_class AS c ON c.oid = l.relation WHERE c.relnamespace = 'archive_alertas_regionais'::regnamespace AND c.relname = 'alerta_mrj' AND l.mode = 'ShareLock' AND l.granted")" == 1 ]]; then
    lock_ready=1
    break
  fi
  sleep 1
done
[[ "$lock_ready" == 1 ]] || {
  kill "$lock_pid" 2>/dev/null || true
  wait "$lock_pid" || true
  printf 'lock fixture did not acquire the expected lock\n' >&2
  exit 1
}
expect_fail lock_preflight env PGDATABASE="$lock_db" "$WORKFLOW" remove --package "$lock_package" --confirm-database "$lock_db" --confirm-remove REMOVE_NINE_ARCHIVE_SCHEMAS
kill "$lock_pid" 2>/dev/null || true
wait "$lock_pid" || true
assert_archive_count "$lock_db" 9

printf 'positive_package=%s\n' "$positive_package"
printf 'package_negative_base=%s\n' "$base_package"
printf 'negative_tests=20\n'
