services:
  frontend:
    build:
      context: ..
      dockerfile: containers/nextjs/Dockerfile
      target: deps
    environment:
        NODE_ENV: development
        WATCHPACK_POLLING: "true"
    volumes:
      - ../frontend/:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  postgres:
    volumes:
      - "${HOST_PGDATA:-/opt/data/infodengue/dev/pgdata}:/var/lib/postgresql/data"

  web:
    stdin_open: true
    tty: true
    command: ["python", "manage.py", "runserver", "-v 3", "0.0.0.0:8000"]
    environment:
      DEBUG: 1
    volumes:
      - ../AlertaDengue/:/opt/services/AlertaDengue
      - type: bind
        source: "${DOCKER_HOST_TECHNICAL_REPORTS_DIR:-/srv/workspace/infodengue/technical_reports}"
        target: /opt/services/technical_reports
        read_only: true

  celery:
    environment:
      DJANGO_SETTINGS_MODULE: "ad_main.settings.dev"
      DEBUG: "True"
    volumes:
      - ../AlertaDengue/:/opt/services/AlertaDengue
