version: "3.4"
services:

  web:
    build:
      context: ".."
      dockerfile: "containers/web/Dockerfile-prod"
      args:
        IMAGE_BUILD: infodengue-prod_base:latest
    env_file:
      - ../.env
    volumes:
      - ${DOCKER_HOST_STATIC}:/opt/services/staticfiles
    ports:
      - 8000:8000
    command: ["/opt/services/AlertaDengue/runwsgi.sh"]

  worker:
    image: infodengue-prod_base:latest
