version: "3.4"
services:
  memcached:
    networks:
      - default

  rabbitmq:
    networks:
      - default

  db:
    build:
      context: ".."
      dockerfile: "containers/postgres/Dockerfile"
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "md5"
    hostname: db
    networks:
      - default
    ports:
      - ${PSQL_PORT}:${PSQL_PORT}
    expose:
      - ${PSQL_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres/dev_dumps:/dumps
    command: -p ${PSQL_PORT} # postgres -c max_wal_size=3GB
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${PSQL_PORT} -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: -p ${PSQL_PORT}

  web:
    # entrypoint: ["/entrypoint.sh"]
    image: infodengue-dev_base:latest
    env_file:
      - ../.env
    ports:
      - 8080:8000
    networks:
      - default
    command: ["python", "manage.py", "runserver"]

  worker:
    networks:
      - default
    depends_on:
      - rabbitmq
    restart: always

volumes:
  postgres_data:

networks:
  default:
      driver: bridge
