version: "3.4"
services:

  web:
    build:
      context: ".."
      dockerfile: "containers/web/Dockerfile-prod"
      args:
        IMAGE_BUILD: infodengue-prod_base:latest
    env_file:
      - ../.env
    ports:
      - 8000:8000
    command: ["/opt/services/AlertaDengue/runwsgi.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s  # requires docker-compose 3.4

  worker:
    image: infodengue-prod_base:latest
    restart: always
