services:
  memcached:
    image: memcached:alpine
    entrypoint:
      - memcached
      - -m
      - "64"
    ports:
      - "${MEMCACHED_PORT}:11211"
    expose:
      - "11211"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - infodengue

  rabbitmq:
    image: rabbitmq:3-alpine
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - infodengue

  redis:
    platform: linux/amd64
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - redis-data:/data
    networks:
      - infodengue

  postgres:
    hostname: postgres
    restart: unless-stopped  
    build:
      context: ".."
      dockerfile: "containers/postgres/Dockerfile"
      args:
        HOST_UID: "${HOST_UID}"
        HOST_GID: "${HOST_GID}"
    env_file:
      - ../.envs/.env
    shm_size: "8gb"
    environment:
      POSTGRES_PASSWORD: "${PSQL_PASSWORD}"
      POSTGRES_DB: "${PSQL_DB}"
      POSTGRES_USER: "${PSQL_USER}"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      PG_RESTORE_STAGING: "${PG_RESTORE_STAGING}"
    ports:
      - "${PSQL_PORT}:5432"
    user: ${HOST_UID}:${HOST_GID}
    volumes:
      # - "${PG_DATA:-/opt/data/infodengue/${ENV}/pgdata}:/var/lib/postgresql/data"
      - ../containers/postgres/setup/:/docker-entrypoint-initdb.d/compose
      - ../containers/postgres/dumps/:/dumps/
    command:
      - -p
      - "${PSQL_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -p ${PSQL_PORT} -U ${PSQL_USER}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - infodengue

  base:
    build:
      context: ".."
      dockerfile: "containers/web/Dockerfile"
      args:
        HOST_UID: "${HOST_UID}"
        HOST_GID: "${HOST_GID}"
        ENV: "${ENV}"
    env_file:
      - ../.envs/.env
    environment:
      MEMCACHED_HOST: "memcached"
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672"
      PSQL_HOST: "${PSQL_HOST}"
      PSQL_PORT: "${PSQL_PORT}"
    volumes:
      - "${DOCKER_HOST_UPLOADED_FILES_DIR}:/MEDIA_ROOT"
      - "${DOCKER_HOST_IMPORTED_FILES_DIR}:/IMPORTED_FILES"
      - "${DOCKER_HOST_DBF_SINAN}:/DBF_SINAN"
      - "${DOCKER_HOST_SHAPEFILES_DIR}:/srv/deploy/shapefile"
      - "${DOCKER_HOST_TEMP_PARQUET_DIR}:/tmp/dbf_parquet"
    user: "${HOST_UID}:${HOST_GID}"

  web:
    extends: base
    hostname: web
    environment:
      DJANGO_PORT: "${DJANGO_PORT}"
      DJANGO_SETTINGS_MODULE: "ad_main.settings.${ENV}"
      DEBUG: "${DEBUG}"
      MAINTENANCE_MODE: "${MAINTENANCE_MODE}"     
    env_file:
      - ../.envs/.env
    ports:
      - "${DJANGO_PORT}:8000"
    entrypoint: ["bash", "/opt/entrypoint.sh"]
    depends_on:
      memcached:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    healthcheck:
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 40s
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8000/status/ || exit 1",
        ]
    networks:
      - infodengue

  celery:
    extends: base
    hostname: celery
    entrypoint: ["bash", "/opt/entrypoint.sh", "/opt/runcelery.sh"]
    env_file:
      - ../.envs/.env
    environment:
      DJANGO_SETTINGS_MODULE: "ad_main.settings.${ENV}"
      CELERY_WORKER_CONCURRENCY: ${CELERY_WORKER_CONCURRENCY:-4}
      CELERY_WORKER_POOL: ${CELERY_WORKER_POOL:-prefork}
      CELERY_LOGLEVEL: ${CELERY_LOGLEVEL:-INFO}
    volumes:
      - ${DOCKER_HOST_UPLOADED_FILES_DIR}:/MEDIA_ROOT
      - ${DOCKER_HOST_IMPORTED_FILES_DIR}:/IMPORTED_FILES
      - ${DOCKER_HOST_DBF_SINAN}:/DBF_SINAN
      - ${DOCKER_HOST_TEMP_PARQUET_DIR}:/tmp/dbf_parquet
      - ${EPISCANNER_HOST_DIR}:/opt/services/episcanner
    user: ${HOST_UID}:${HOST_GID}
    depends_on:
      memcached:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - infodengue
    healthcheck:
        test: ["CMD-SHELL", "celery -A ad_main.celeryapp:app inspect ping --destination celery@$$HOSTNAME | grep -q OK"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 10s

volumes:
  redis-data:

networks:
  infodengue:
    driver: bridge
