services:
  minio:
    image: minio/minio:RELEASE.2024-03-30T09-41-56Z # Use latest stable
    container_name: minio-server
    restart: unless-stopped
    ports:
      - "${MINIO_PORT_1:-9000}:9000" # S3 API
      - "${MINIO_PORT_2:-9001}:9001" # Web Console
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-admin}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-SuperSecretPassword123!}"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "/usr/bin/mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: Automatically create the buckets on first boot
  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-admin} ${MINIO_ROOT_PASSWORD:-SuperSecretPassword123!} &&
      /usr/bin/mc mb -p myminio/sinan-prod &&
      /usr/bin/mc mb -p myminio/sinan-staging &&
      /usr/bin/mc ilm add --expire-days 7 myminio/sinan-staging;
      exit 0;
      "

  minio-materializer:
    image: minio/mc:latest
    container_name: minio-materializer
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - ../.envs/.env
    volumes:
      - ${DOCKER_HOST_INCOMING_DIR}:/incoming
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-admin} ${MINIO_ROOT_PASSWORD:-SuperSecretPassword123!} &&
      echo '[II] Starting mc mirror --watch...' &&
      /usr/bin/mc mirror --watch --overwrite myminio/sinan-staging /incoming;
      "

volumes:
  minio_data:
    driver: local
