services:
  postgres:
    environment:
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - "${HOST_PGDATA:-/opt/data/infodengue/prod/pgdata}:/var/lib/postgresql/data"
    command:
      - postgres
      - -p
      - "5432"
      - -c
      - "unix_socket_directories=/var/run/postgresql"
      - -c
      - "max_worker_processes=8"

  web:
    command: /opt/runwsgi.sh
    environment:
      DEBUG: 0
      DJANGO_SETTINGS_MODULE: "ad_main.settings.prod"
    volumes:
      - ../AlertaDengue/:/opt/services/AlertaDengue
      - type: bind
        source: "${DOCKER_HOST_TECHNICAL_REPORTS_DIR:-${HOME}/technical_reports}"
        target: /opt/services/technical_reports
        read_only: true
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - memcached

  celery:
    environment:
      DJANGO_SETTINGS_MODULE: "ad_main.settings.prod"
      DEBUG: 0
    volumes:
      - ../AlertaDengue/:/opt/services/AlertaDengue
