services:
  postgres:
    volumes:
      - type: bind
        source: ${PGBACKREST_CONFIG_FILE:-../.runtime/pgbackrest/pgbackrest-${ENV}.conf}
        target: /etc/pgbackrest/pgbackrest.conf
        read_only: true

  pgbackrest:
    hostname: pgbackrest
    restart: unless-stopped
    user: "${HOST_UID}:${HOST_GID}"
    build:
      context: ..
      dockerfile: containers/pgbackrest/Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    env_file:
      - ../.envs/.env
    command:
      - bash
      - -lc
      - sleep infinity
    volumes:
      - type: bind
        source: ${HOST_PGDATA}
        target: /var/lib/postgresql/data
      - type: volume
        source: pgsocket
        target: /var/run/postgresql
      - type: volume
        source: pgbackrest_repo
        target: /var/lib/pgbackrest
      - type: volume
        source: pgbackrest_logs
        target: /var/log/pgbackrest
      - type: bind
        source: ${PGBACKREST_CONFIG_FILE:-../.runtime/pgbackrest/pgbackrest-${ENV}.conf}
        target: /etc/pgbackrest/pgbackrest.conf
        read_only: true
    networks:
      - infodengue

volumes:
  pgsocket:
  pgbackrest_repo:
  pgbackrest_logs:

networks:
  infodengue:
    driver: bridge
