version: "3.4"
services:
  memcached:
    networks:
      - staging

  rabbitmq:
    networks:
      - staging

  db:
    build:
      context: ".."
      dockerfile: "containers/postgres/Dockerfile"
    env_file:
      - ../.env
    hostname: db
    ports:
      - ${PSQL_PORT}:${PSQL_PORT}
    networks:
      - staging
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/dumps:/dumps
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${PSQL_PORT} -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: -p ${PSQL_PORT}

  web:
    # entrypoint: ["/entrypoint.sh"]
    image: infodengue-dev_base:latest
    env_file:
      - ../.env
    ports:
      - 8080:8000
    networks:
      - staging
    command: ["python", "manage.py", "runserver"]

  worker:
    networks:
      - staging
    depends_on:
      - rabbitmq
    restart: always

networks:
  staging:
      driver: bridge


volumes:
  pg_data:
