services:
  postgres:
    volumes:
      - "${PG_DATA_DEV:-/opt/data/infodengue/dev/pgdata}:/var/lib/postgresql/data"

  web:
    stdin_open: true
    tty: true
    command: ["python", "manage.py", "runserver", "-v 3", "0.0.0.0:8000"]
    environment:
      DEBUG: 1
    volumes:
      - ../AlertaDengue/:/opt/services/AlertaDengue

  celery:
    environment:
      DJANGO_SETTINGS_MODULE: "ad_main.settings.dev"
      DEBUG: "True"
    volumes:
      - ../AlertaDengue/:/opt/services/AlertaDengue
