version: 2


base: &base
  working_directory: ~/repo
  docker:
    - image: continuumio/miniconda3:latest

    
test: &test
  <<: *base
  steps:
    - checkout
    - run:
        name: Update Conda
        command: |
          conda config --set always_yes True
          conda config --add channels conda-forge
          conda install -n base conda
          conda update --all
          conda create python=${PYTHON_VERSION} -n alertadengue --file AlertaDengue/requirements-conda.txt
          conda install python=${PYTHON_VERSION} -n alertadengue --file AlertaDengue/requirements-dev.txt
    - run:
        name: Show the exact environment used
        command: |
          source activate alertadengue
          conda list
    - run:
        name: Run Tests
        command: |
          source activate alertadengue
          cd AlertaDengue
          flake8  
  
jobs:
  python36_test:
      <<: *test
      environment:
        - PYTHON_VERSION: 3.6
  python37_test:
      <<: *test
      environment:
        - PYTHON_VERSION: 3.7

workflows:
  version: 2
  test:
    jobs:
      - python36_test
      - python37_test
