# Generated by Django 3.2.20 on 2023-10-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicoalerta',
            table='"Municipio"."Historico_alerta"',
        ),
    ]
