name: alertadengue
channels:
  - conda-forge
  - defaults
dependencies:
- django=3.0.3
- django-bootstrap4
- ibis-framework
- geojson
- gunicorn
- numpy
- pandas
- pip=19.3
- python=3.7
- python-dotenv
- pytz
- psycopg2
- sqlalchemy
- python-memcached
- django-makemessages-xgettext
- mock
- dbfread
- dj-database-url
- django-chunked-upload=1.1.3
- docker-compose
- celery
- dj-static
- pyproj
- gdal=2.4.2
- fiona
- rasterio
- boto3
- geopy
- geopandas
- sh
- ipython
- sqlparse
- plotly=4.0.0
- BeautifulSoup4
# develop
- jupyterlab
- matplotlib
- flake8
- pillow
- pre-commit
- black
- flake8
- mypy
- pip:
    - django-leaflet==0.26.0
    # develop
    - django-extensions
