--
-- PostgreSQL database
--
SET client_encoding = 'UTF8';
SET default_transaction_read_only = off;
SET standard_conforming_strings = on;

--
-- Roles
-- Create Roles
--
CREATE ROLE "Dengue";
CREATE ROLE "Read_only";
CREATE ROLE "infodenguedev";
CREATE ROLE "administrador";
CREATE ROLE "dengueadmin";
CREATE ROLE "dengue";
CREATE ROLE "forecast";
-- CREATE ROLE "postgres";

--
-- Alter Roles
--
ALTER ROLE "Dengue" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';
ALTER ROLE "dengueadmin" WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD NULL VALID UNTIL 'infinity';
ALTER ROLE "Read_only" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';
ALTER ROLE "infodenguedev" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';
ALTER ROLE "dengue" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';
ALTER ROLE "administrador" WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD NULL;
ALTER ROLE "forecast" WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION VALID UNTIL 'infinity';
ALTER ROLE "postgres" WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION NOBYPASSRLS;
ALTER ROLE "forecast" SET search_path = forecast, public;

--
-- Role memberships
--
GRANT "Dengue" TO dengue GRANTED BY "administrador";
GRANT "Dengue" TO dengueadmin GRANTED BY "administrador";
