version: "3.4"
services:
  memcached:
    image: memcached:alpine
    hostname: memcached
    entrypoint:
      - memcached
      - -m 64
    ports:
      - ${MEMCACHED_PORT}:11211
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s  # requires docker-compose 3.4
    restart: always

  rabbitmq:
    image: rabbitmq:3-alpine
    hostname: rabbitmq
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s  # requires docker-compose 3.4
    restart: always

  base:
    build:
      context: ".."
      dockerfile: "docker/web/Dockerfile-base"
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
        ENV: ${ENV}
    profiles:
      - donotstart

  web:
    # entrypoint: ["/entrypoint.sh"]
    env_file:
      - ../.env
    environment:
      - MEMCACHED_HOST=memcached
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_PORT=${PSQL_PORT}
    volumes:
      - ${DOCKER_HOST_MEDIA_ROOT}:/MEDIA_ROOT
      - ${DOCKER_HOST_IMPORTED_FILES_DIR}:/IMPORTED_FILES
      - ${DOCKER_HOST_SHAPEFILES_DIR}:/srv/deploy/shapefile
      - ${DOCKER_HOST_INCIDENCE_MAPS}:/opt/services/AlertaDengue/static/img/incidence_maps
      - ${DOCKER_HOST_TEMP_PARQUET_DIR}:/tmp/dbfs_parquet
    depends_on:
      - worker
      - rabbitmq
      - memcached
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s  # requires docker-compose 3.4

  worker:
    image: infodengue-dev_base:latest
    entrypoint: ["/opt/services/celery-run.sh"]
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_PORT=${PSQL_PORT}
    volumes:
      - ${DOCKER_HOST_MEDIA_ROOT}:/MEDIA_ROOT
      - ${DOCKER_HOST_IMPORTED_FILES_DIR}:/IMPORTED_FILES
      - ${DOCKER_HOST_TEMP_PARQUET_DIR}:/tmp/dbfs_parquet
    depends_on:
      - rabbitmq
      - memcached
    restart: always
    healthcheck:
      test: ["CMD", "celery", "-A", "ad_main.celeryapp:app", "inspect", "ping"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s  # requires docker-compose 3.4
