ARG IMAGE_BUILD
FROM ${IMAGE_BUILD}

ENV ENV_NAME=alertadengue-dev

USER root

# Configure cron for DBF request
COPY docker/cron-tasks /etc/cron.d/cron-tasks
RUN chmod 0644 /etc/cron.d/cron-tasks \
  && crontab -u deploy /etc/cron.d/cron-tasks \
  && echo "deploy"  > /etc/cron.allow \
  && touch /var/log/cron.log \
  && chown deploy:deploy /var/log/cron.log

RUN echo 'source /opt/conda/bin/activate "$ENV_NAME" && exec "$@"' > /activate.sh \
  && chmod +x /activate.sh \
  && echo 'source activate "$ENV_NAME"' >  /home/deploy/.bashrc

ENV PATH "$PATH:/home/deploy/.local/bin"
ENV PATH /opt/conda/envs/$ENV_NAME/bin:$PATH

COPY --chown=deploy:deploy docker/test.sh /opt/services
RUN chmod +x /opt/services/test.sh

USER deploy

# Use environment to update the env alertadengue
RUN mamba env create -n $ENV_NAME \
    --file /tmp/environment.yaml \
  && cd /opt/services/AlertaDengue && poetry config virtualenvs.create false && poetry install \
  && conda clean --all \
  && find /opt/conda/ -type f,l -name '*.a' -delete \
  && find /opt/conda/ -type f,l -name '*.pyc' -delete \
  && find /opt/conda/ -type f,l -name '*.js.map' -delete \
  && rm -rf /opt/conda/pkgs
