FROM condaforge/mambaforge

ARG HOST_UID
ARG HOST_GID
ARG SERVICES
ENV ENV_NAME=alertadengue
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update --yes \
  && apt-get -qq install --yes --no-install-recommends \
  build-essential git make postgresql-client vim \
  ca-certificates wget locales cron sudo \
  && rm -rf /var/lib/apt/lists/*

#Set locale
RUN sed -i -e "s/# pt_BR.*/pt_BR.UTF-8 UTF-8/" /etc/locale.gen \
  && dpkg-reconfigure --frontend=noninteractive locales \
  && update-locale LANG=pt_BR.UTF-8

# Create deploy user
RUN addgroup --gid ${HOST_GID} deploy \
  && useradd --uid ${HOST_UID} --gid ${HOST_GID} -ms /bin/bash deploy \
  && echo "deploy ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/deploy \
  && chmod 0440 /etc/sudoers.d/deploy \
  && export ENV_NAME="$ENV_NAME" \
  && mkdir -p /opt/conda /opt/services/logs /opt/services/AlertaDengue/ \
  && chmod -R a+rwx /opt/conda /opt/services/AlertaDengue/ /tmp \
  && chown deploy:deploy /opt/services/ /tmp \
  && echo 'source /opt/conda/bin/activate "$ENV_NAME" && exec "$@"' > /activate.sh \
  && echo 'source activate "$ENV_NAME"' >  /home/deploy/.bashrc \
  # Export ENV variables to use in Crontab
  && printenv | sed 's/^\(.*\)$/export \1/g' >> /preload.sh \
  && chmod +x /activate.sh

ENV PATH "$PATH:/home/deploy/.local/bin"
ENV PATH /opt/conda/envs/$ENV_NAME/bin:$PATH

USER deploy

## Copy code to the container with permissions to user
COPY --chown=deploy:deploy AlertaDengue  /opt/services/AlertaDengue
COPY --chown=deploy env.tpl pyproject.toml poetry.lock  /opt/services/AlertaDengue/
COPY --chown=deploy:deploy conda/environment.yaml /tmp/environment.yaml

# Use environment to update the env alertadengue
RUN mamba env create -n $ENV_NAME \
    --file /tmp/environment.yaml \
  && cd /opt/services/AlertaDengue && poetry config virtualenvs.create false && poetry install --no-dev \
  && conda clean --all \
  && find /opt/conda/ -type f,l -name '*.a' -delete \
  && find /opt/conda/ -type f,l -name '*.pyc' -delete \
  && find /opt/conda/ -type f,l -name '*.js.map' -delete \
  && rm -rf /opt/conda/pkgs

COPY --chown=deploy:deploy docker/entrypoint.sh /entrypoint.sh
WORKDIR /opt/services/AlertaDengue
ENTRYPOINT ["bash", "/activate.sh"]
