FROM continuumio/miniconda3

RUN apt-get -qq update --yes \
 && apt-get -qq install --yes --no-install-recommends \
        postgresql-client \
        build-essential \
        libpq-dev \
        libgdal-dev \
        ca-certificates locales \
 && rm -rf /var/lib/apt/lists/*

#Set locale
RUN sed -i -e "s/# pt_BR.*/pt_BR.UTF-8 UTF-8/" /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG=pt_BR.UTF-8

ARG PYTHON_VERSION
COPY environment-${PYTHON_VERSION}.yml /tmp/environment.yml

RUN /opt/conda/bin/conda config --add channels conda-forge \
  && /opt/conda/bin/conda update --all --yes --quiet \
  && /opt/conda/bin/conda env update --name base --file /tmp/environment.yml \
  && /opt/conda/bin/conda install --yes conda-build \
  && /opt/conda/bin/conda clean --all --yes

ENV PATH="/opt/conda/bin:${PATH}"

# Create deploy user
COPY docker/prepare_permission.sh /prepare_permission.sh
ARG HOST_UID
ARG HOST_GID
RUN /prepare_permission.sh

# copy code to the container and attribute permissions to user
RUN mkdir /srv/deploy/logs \
  && chown -R deploy:celery /srv/deploy/logs
# folders
COPY --chown=deploy:celery docker  /srv/deploy/docker
COPY --chown=deploy:celery AlertaDengue  /srv/deploy/AlertaDengue
# files
COPY --chown=deploy:celery requirements.txt example_env_file /srv/deploy/

WORKDIR /srv/deploy/AlertaDengue

RUN cp -p /srv/deploy/example_env_file /srv/deploy/.env_staging

USER deploy

CMD ["/srv/deploy/AlertaDengue/run_celery_worker.sh"]
