ARG IMAGE_BUILD
FROM ${IMAGE_BUILD}

USER root

# Configure cron for DBF request
COPY docker/cron-tasks /etc/cron.d/cron-tasks
RUN chmod 0644 /etc/cron.d/cron-tasks \
  && crontab -u deploy /etc/cron.d/cron-tasks \
  && echo "deploy"  > /etc/cron.allow \
  && touch /var/log/cron.log \
  && chown deploy:deploy /var/log/cron.log

USER deploy

# EXPOSE 8000
