name: alertadengue
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.*
  - poetry
  - pip
  - gdal>=3.6,<3.9
  - psycopg2-binary
  - pip:
      - compose-go >=2.20.2,<2.31.0
      - containers-sugar >=1.19,<2.0
      - makim==1.27.0
      - pyogrio
