name: alertadengue
channels:
  - nodefaults
  - conda-forge
dependencies:
  - django >=3.1.8,<4
  - gdal 3.3.*
  - pip
  - poetry
  - psycopg2-binary
  - python 3.10.*
  - urllib3 = 1.26.15 # https://github.com/psf/requests/issues/1096
  - pip:
    - containers-sugar ==1.7.0
    - makim ==1.8.1
