# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 19:27
from __future__ import unicode_literals

import dbf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('export_date', models.DateField()),
                ('notification_year', models.IntegerField(default=dbf.models.current_year)),
            ],
        ),
    ]
