# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('dbf', '0004_auto_20170323_0122')]

    operations = [
        migrations.AddField(
            model_name='dbf',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=255),
        )
    ]
