# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 10:26
from __future__ import unicode_literals

import chunked_upload.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('dbf', '0005_dbf_municipio')]

    operations = [
        migrations.AlterField(
            model_name='dbfchunkedupload',
            name='file',
            field=models.FileField(
                max_length=255,
                upload_to=chunked_upload.settings.default_upload_to,
            ),
        )
    ]
