# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 22:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('dbf', '0006_auto_20171114_1026')]

    operations = [
        migrations.AlterField(
            model_name='dbf',
            name='uploaded_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
