# Generated by Django 3.2.25 on 2025-02-18 21:35

import ad_main.settings
import chunked_upload.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbf', '0009_auto_20210901_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbfchunkedupload',
            name='file',
            field=models.FileField(max_length=255, storage=ad_main.settings.DBFSINANStorage(), upload_to=chunked_upload.settings.default_upload_to),
        ),
    ]
