--
-- Development roles
--
CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION NOBYPASSRLS;
CREATE ROLE dengueuser LOGIN PASSWORD 'denguepassword';
ALTER ROLE dengueuser WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION VALID UNTIL 'infinity';
CREATE ROLE forecastuser;
ALTER ROLE forecastuser WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION VALID UNTIL 'infinity';
CREATE ROLE "Read_only";
ALTER ROLE "Read_only" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';

--
-- Development database
--
CREATE DATABASE denguedb WITH OWNER dengueuser ENCODING 'utf-8';
CREATE DATABASE infodenguedb WITH OWNER dengueuser ENCODING 'utf-8';
