# Generated by Django 3.1.6 on 2021-04-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_auto_20180124_2239'),
    ]

    operations = [
        migrations.RemoveField(model_name='forecastmodel', name='weeks',),
        migrations.AddField(
            model_name='forecastmodel',
            name='filename',
            field=models.FileField(
                default='Trained model', upload_to='uploads/%Y/%m/%d/'
            ),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='github',
            field=models.URLField(
                default='github.com',
                help_text='URL do repositório github',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='train_end',
            field=models.DateField(
                default='timezone.now', help_text='Data Final'
            ),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='train_start',
            field=models.DateField(
                default='timezone.now', help_text='Data Inicio'
            ),
        ),
        migrations.AlterField(
            model_name='forecastmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='forecastmodel', table='forecast"."forecast_table',
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('se', models.IntegerField(help_text='Epidemiological Week')),
                (
                    'se_predicted',
                    models.IntegerField(help_text='Predicted Week'),
                ),
                ('active', models.BooleanField(help_text='Está ativo?')),
                (
                    'model',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='forecast.forecastmodel',
                    ),
                ),
            ],
            options={'db_table': 'forecast"."forecast_model'},
        ),
    ]
