STATE_NAMES = [
    {
        "state_abbv": "AC",
        "state_name": "Acre",
        "map_zoom": 6,
        "lat": -8.77,
        "long": -70.55,
    },
    {
        "state_abbv": "AL",
        "state_name": "Alagoas",
        "map_zoom": 6,
        "lat": -9.71,
        "long": -35.73,
    },
    {
        "state_abbv": "AM",
        "state_name": "Amazonas",
        "map_zoom": 6,
        "lat": -3.07,
        "long": -61.66,
    },
    {
        "state_abbv": "AP",
        "state_name": "Amapá",
        "map_zoom": 6,
        "lat": 1.41,
        "long": -51.77,
    },
    {
        "state_abbv": "BA",
        "state_name": "Bahia",
        "map_zoom": 6,
        "lat": -12.96,
        "long": -38.51,
    },
    {
        "state_abbv": "CE",
        "state_name": "Ceará",
        "map_zoom": 6,
        "lat": -3.71,
        "long": -38.54,
    },
    {
        "state_abbv": "DF",
        "state_name": "Distrito Federal",
        "map_zoom": 6,
        "lat": -15.83,
        "long": -47.86,
    },
    {
        "state_abbv": "ES",
        "state_name": "Espírito Santo",
        "map_zoom": 6,
        "lat": -19.19,
        "long": -40.34,
    },
    {
        "state_abbv": "GO",
        "state_name": "Goiás",
        "map_zoom": 6,
        "lat": -16.64,
        "long": -49.31,
    },
    {
        "state_abbv": "MA",
        "state_name": "Maranhão",
        "map_zoom": 6,
        "lat": -2.55,
        "long": -44.30,
    },
    {
        "state_abbv": "MG",
        "state_name": "Minas Gerais",
        "map_zoom": 6,
        "lat": -18.10,
        "long": -44.38,
    },
    {
        "state_abbv": "MS",
        "state_name": "Mato Grosso do Sul",
        "map_zoom": 6,
        "lat": -20.51,
        "long": -54.54,
    },
    {
        "state_abbv": "MT",
        "state_name": "Mato Grosso",
        "map_zoom": 6,
        "lat": -12.64,
        "long": -55.42,
    },
    {
        "state_abbv": "PA",
        "state_name": "Pará",
        "map_zoom": 6,
        "lat": -5.53,
        "long": -52.29,
    },
    {
        "state_abbv": "PB",
        "state_name": "Paraíba",
        "map_zoom": 6,
        "lat": -7.06,
        "long": -35.55,
    },
    {
        "state_abbv": "PE",
        "state_name": "Pernambuco",
        "map_zoom": 6,
        "lat": -8.28,
        "long": -35.07,
    },
    {
        "state_abbv": "PI",
        "state_name": "Piauí",
        "map_zoom": 6,
        "lat": -8.28,
        "long": -43.68,
    },
    {
        "state_abbv": "PR",
        "state_name": "Paraná",
        "map_zoom": 6,
        "lat": -24.89,
        "long": -51.55,
    },
    {
        "state_abbv": "RJ",
        "state_name": "Rio de Janeiro",
        "map_zoom": 6,
        "lat": -22.84,
        "long": -43.15,
    },
    {
        "state_abbv": "RN",
        "state_name": "Rio Grande do Norte",
        "map_zoom": 6,
        "lat": -5.22,
        "long": -36.52,
    },
    {
        "state_abbv": "RO",
        "state_name": "Rondônia",
        "map_zoom": 6,
        "lat": -11.22,
        "long": -62.80,
    },
    {
        "state_abbv": "RR",
        "state_name": "Roraima",
        "map_zoom": 6,
        "lat": 1.89,
        "long": -61.22,
    },
    {
        "state_abbv": "RS",
        "state_name": "Rio Grande do Sul",
        "map_zoom": 6,
        "lat": -30.01,
        "long": -51.22,
    },
    {
        "state_abbv": "SC",
        "state_name": "Santa Catarina",
        "map_zoom": 6,
        "lat": -27.33,
        "long": -49.44,
    },
    {
        "state_abbv": "SE",
        "state_name": "Sergipe",
        "map_zoom": 6,
        "lat": -10.90,
        "long": -37.07,
    },
    {
        "state_abbv": "SP",
        "state_name": "São Paulo",
        "map_zoom": 6,
        "lat": -23.55,
        "long": -46.64,
    },
    {
        "state_abbv": "TO",
        "state_name": "Tocantins",
        "map_zoom": 6,
        "lat": -10.25,
        "long": -48.25,
    },
]
