# Generated by Django 5.2.11 on 2026-03-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CID10",
            fields=[
                (
                    "code",
                    models.CharField(
                        db_column="codigo",
                        help_text="Código do doença",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="nome",
                        help_text="Nome da doença",
                        max_length=512,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cities",
                "db_table": '"Dengue_global"."CID10"',
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "geocode",
                    models.IntegerField(
                        db_column="geocodigo",
                        help_text="Código do Município",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="nome",
                        help_text="Nome do municipio",
                        max_length=128,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        db_column="uf",
                        help_text="Nome do estado",
                        max_length=20,
                    ),
                ),
                (
                    "id_regional",
                    models.IntegerField(
                        db_column="id_regional",
                        help_text="Geocódigo da Regional de Saúde",
                    ),
                ),
                (
                    "regional",
                    models.CharField(
                        db_column="regional",
                        help_text="Nome da Regional de Saúde",
                        max_length=128,
                    ),
                ),
                (
                    "macroregional_id",
                    models.IntegerField(
                        db_column="macroregional_id",
                        help_text="Geocódigo da Macroregional de Saúde",
                    ),
                ),
                (
                    "macroregional",
                    models.CharField(
                        db_column="macroregional",
                        help_text="Nome da Regional de Saúde",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cities",
                "db_table": '"Dengue_global"."Municipio"',
            },
        ),
        migrations.CreateModel(
            name="ParameterUF",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.IntegerField()),
                ("state_abbr", models.CharField(max_length=2)),
                ("state_name", models.TextField()),
                ("cid10", models.CharField(max_length=16)),
                ("limiar_preseason", models.FloatField(blank=True, null=True)),
                ("limiar_posseason", models.FloatField(blank=True, null=True)),
                ("limiar_epidemico", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": '"Dengue_global"."parameters_uf"',
                "indexes": [
                    models.Index(
                        fields=["state_code"],
                        name="parameters_uf_idx_state_code",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("state_code", "cid10"),
                        name="parameters_uf_uniq_state_code_cid10",
                    )
                ],
            },
        ),
    ]
