# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dengue_2010',
        ),
        migrations.DeleteModel(
            name='Dengue_2011',
        ),
        migrations.DeleteModel(
            name='Dengue_2012',
        ),
        migrations.DeleteModel(
            name='Dengue_2013',
        ),
        migrations.DeleteModel(
            name='DengueConfirmados_2013',
        ),
    ]
