# Generated by Django 5.2.11 on 2026-03-23 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cid10",
            options={
                "managed": False,
                "verbose_name": "CID10",
                "verbose_name_plural": "CID10 codes",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={
                "managed": False,
                "verbose_name": "city",
                "verbose_name_plural": "cities",
            },
        ),
        migrations.AlterModelOptions(
            name="parameteruf",
            options={
                "verbose_name": "UF parameter",
                "verbose_name_plural": "UF parameters",
            },
        ),
        migrations.RemoveConstraint(
            model_name="parameteruf",
            name="parameters_uf_uniq_state_code_cid10",
        ),
        migrations.RemoveField(
            model_name="parameteruf",
            name="id",
        ),
        migrations.AddField(
            model_name="parameteruf",
            name="pk",
            field=models.CompositePrimaryKey(
                "state_code",
                "cid10",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="parameteruf",
            name="cid10",
            field=models.ForeignKey(
                db_column="cid10",
                help_text="Código CID10 da doença",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dados.cid10",
            ),
        ),
        migrations.AlterField(
            model_name="parameteruf",
            name="limiar_epidemico",
            field=models.FloatField(
                blank=True,
                db_column="limiar_epidemico",
                help_text="Limiar epidêmico",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parameteruf",
            name="limiar_posseason",
            field=models.FloatField(
                blank=True,
                db_column="limiar_posseason",
                help_text="Limiar de pós-sazonalidade",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parameteruf",
            name="limiar_preseason",
            field=models.FloatField(
                blank=True,
                db_column="limiar_preseason",
                help_text="Limiar de pré-sazonalidade",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parameteruf",
            name="state_abbr",
            field=models.CharField(
                db_column="state_abbr",
                help_text="Sigla do estado",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="parameteruf",
            name="state_code",
            field=models.IntegerField(
                db_column="state_code", help_text="Código numérico do estado"
            ),
        ),
        migrations.AlterField(
            model_name="parameteruf",
            name="state_name",
            field=models.TextField(
                db_column="state_name", help_text="Nome do estado"
            ),
        ),
    ]
