# Generated by Django 5.2.11 on 2026-03-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados", "0002_alter_cid10_options_alter_city_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameteruf",
            name="cid10",
            field=models.CharField(
                db_column="cid10",
                help_text="Código CID10 da doença",
                max_length=16,
            ),
        ),
    ]
