# Generated by Django 5.2.11 on 2026-07-16 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados", "0005_create_notification_api_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpiscannerSirParams",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid10", models.CharField(max_length=10)),
                ("year", models.IntegerField()),
                ("ep_ini", models.CharField(blank=True, max_length=20, null=True)),
                ("ep_pw", models.CharField(max_length=20)),
                ("ep_end", models.CharField(blank=True, max_length=20, null=True)),
                ("ep_dur", models.IntegerField(blank=True, null=True)),
                ("peak_week", models.FloatField()),
                ("beta", models.FloatField()),
                ("gamma", models.FloatField()),
                ("r0", models.FloatField()),
                ("total_cases", models.FloatField()),
                ("alpha", models.FloatField()),
                ("sum_res", models.FloatField()),
                ("t_ini", models.IntegerField(blank=True, null=True)),
                ("t_end", models.IntegerField(blank=True, null=True)),
                (
                    "geocode",
                    models.ForeignKey(
                        db_column="geocode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dados.city",
                    ),
                ),
            ],
            options={
                "db_table": '"episcanner"."sir_params"',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cid10", "geocode", "year"),
                        name="uq_sir_params_cid10_geocode_year",
                    )
                ],
            },
        ),
    ]
