# Generated by Django 5.2.11 on 2026-08-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados", "0006_episcanner_sir_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyHistoricalAlertChikungunya",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "epidemiological_week_start_date",
                    models.DateField(db_column="data_iniSE"),
                ),
                ("epidemiological_week", models.IntegerField(db_column="SE")),
                (
                    "estimated_cases",
                    models.FloatField(db_column="casos_est", null=True),
                ),
                (
                    "estimated_cases_min",
                    models.IntegerField(db_column="casos_est_min", null=True),
                ),
                (
                    "estimated_cases_max",
                    models.IntegerField(db_column="casos_est_max", null=True),
                ),
                ("cases", models.IntegerField(db_column="casos", null=True)),
                ("rt1_probability", models.FloatField(db_column="p_rt1", null=True)),
                (
                    "incidence_100k_probability",
                    models.FloatField(db_column="p_inc100k", null=True),
                ),
                (
                    "locality_id",
                    models.IntegerField(db_column="Localidade_id", null=True),
                ),
                ("alert_level", models.SmallIntegerField(db_column="nivel", null=True)),
                (
                    "model_version",
                    models.CharField(
                        db_column="versao_modelo", max_length=40, null=True
                    ),
                ),
                (
                    "municipality_name",
                    models.CharField(
                        db_column="municipio_nome", max_length=128, null=True
                    ),
                ),
                (
                    "municipality_geocode",
                    models.IntegerField(db_column="municipio_geocodigo"),
                ),
                ("probable_cases", models.IntegerField(db_column="casprov", null=True)),
                (
                    "estimated_probable_cases",
                    models.FloatField(db_column="casprov_est", null=True),
                ),
                (
                    "estimated_probable_cases_min",
                    models.IntegerField(db_column="casprov_est_min", null=True),
                ),
                (
                    "estimated_probable_cases_max",
                    models.IntegerField(db_column="casprov_est_max", null=True),
                ),
                (
                    "confirmed_cases",
                    models.IntegerField(db_column="casconf", null=True),
                ),
            ],
            options={
                "db_table": '"Municipio"."Historico_alerta_chik"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyHistoricalAlertDengue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "epidemiological_week_start_date",
                    models.DateField(db_column="data_iniSE"),
                ),
                ("epidemiological_week", models.IntegerField(db_column="SE")),
                (
                    "estimated_cases",
                    models.FloatField(db_column="casos_est", null=True),
                ),
                (
                    "estimated_cases_min",
                    models.IntegerField(db_column="casos_est_min", null=True),
                ),
                (
                    "estimated_cases_max",
                    models.IntegerField(db_column="casos_est_max", null=True),
                ),
                ("cases", models.IntegerField(db_column="casos", null=True)),
                ("rt1_probability", models.FloatField(db_column="p_rt1", null=True)),
                (
                    "incidence_100k_probability",
                    models.FloatField(db_column="p_inc100k", null=True),
                ),
                (
                    "locality_id",
                    models.IntegerField(db_column="Localidade_id", null=True),
                ),
                ("alert_level", models.SmallIntegerField(db_column="nivel", null=True)),
                (
                    "model_version",
                    models.CharField(
                        db_column="versao_modelo", max_length=40, null=True
                    ),
                ),
                (
                    "municipality_name",
                    models.CharField(
                        db_column="municipio_nome", max_length=128, null=True
                    ),
                ),
                (
                    "municipality_geocode",
                    models.IntegerField(db_column="municipio_geocodigo"),
                ),
                ("probable_cases", models.IntegerField(db_column="casprov", null=True)),
                (
                    "estimated_probable_cases",
                    models.FloatField(db_column="casprov_est", null=True),
                ),
                (
                    "estimated_probable_cases_min",
                    models.IntegerField(db_column="casprov_est_min", null=True),
                ),
                (
                    "estimated_probable_cases_max",
                    models.IntegerField(db_column="casprov_est_max", null=True),
                ),
                (
                    "confirmed_cases",
                    models.IntegerField(db_column="casconf", null=True),
                ),
            ],
            options={
                "db_table": '"Municipio"."Historico_alerta"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyHistoricalAlertZika",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "epidemiological_week_start_date",
                    models.DateField(db_column="data_iniSE"),
                ),
                ("epidemiological_week", models.IntegerField(db_column="SE")),
                (
                    "estimated_cases",
                    models.FloatField(db_column="casos_est", null=True),
                ),
                (
                    "estimated_cases_min",
                    models.IntegerField(db_column="casos_est_min", null=True),
                ),
                (
                    "estimated_cases_max",
                    models.IntegerField(db_column="casos_est_max", null=True),
                ),
                ("cases", models.IntegerField(db_column="casos", null=True)),
                ("rt1_probability", models.FloatField(db_column="p_rt1", null=True)),
                (
                    "incidence_100k_probability",
                    models.FloatField(db_column="p_inc100k", null=True),
                ),
                (
                    "locality_id",
                    models.IntegerField(db_column="Localidade_id", null=True),
                ),
                ("alert_level", models.SmallIntegerField(db_column="nivel", null=True)),
                (
                    "model_version",
                    models.CharField(
                        db_column="versao_modelo", max_length=40, null=True
                    ),
                ),
                (
                    "municipality_name",
                    models.CharField(
                        db_column="municipio_nome", max_length=128, null=True
                    ),
                ),
                (
                    "municipality_geocode",
                    models.IntegerField(db_column="municipio_geocodigo"),
                ),
                ("probable_cases", models.IntegerField(db_column="casprov", null=True)),
                (
                    "estimated_probable_cases",
                    models.FloatField(db_column="casprov_est", null=True),
                ),
                (
                    "estimated_probable_cases_min",
                    models.IntegerField(db_column="casprov_est_min", null=True),
                ),
                (
                    "estimated_probable_cases_max",
                    models.IntegerField(db_column="casprov_est_max", null=True),
                ),
                (
                    "confirmed_cases",
                    models.IntegerField(db_column="casconf", null=True),
                ),
            ],
            options={
                "db_table": '"Municipio"."Historico_alerta_zika"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MacroRegion",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="nome", max_length=128)),
            ],
            options={
                "db_table": '"Dengue_global"."macroregional"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "notification_date",
                    models.DateField(db_column="dt_notific", null=True),
                ),
                (
                    "notification_week",
                    models.IntegerField(db_column="se_notif", null=True),
                ),
                (
                    "notification_year",
                    models.IntegerField(db_column="ano_notif", null=True),
                ),
                (
                    "symptom_onset_date",
                    models.DateField(db_column="dt_sin_pri", null=True),
                ),
                (
                    "symptom_onset_week",
                    models.IntegerField(db_column="se_sin_pri", null=True),
                ),
                ("entry_date", models.DateField(db_column="dt_digita", null=True)),
                (
                    "municipality_geocode",
                    models.IntegerField(db_column="municipio_geocodigo"),
                ),
                (
                    "notification_number",
                    models.CharField(db_column="nu_notific", max_length=64),
                ),
                (
                    "cid10_code",
                    models.CharField(db_column="cid10_codigo", max_length=16),
                ),
                ("birth_date", models.DateField(db_column="dt_nasc", null=True)),
                ("sex", models.CharField(db_column="cs_sexo", max_length=1, null=True)),
                (
                    "age_code",
                    models.CharField(db_column="nu_idade_n", max_length=8, null=True),
                ),
                (
                    "final_classification",
                    models.CharField(db_column="classi_fin", max_length=8, null=True),
                ),
                (
                    "criteria",
                    models.CharField(db_column="criterio", max_length=8, null=True),
                ),
                (
                    "district_id",
                    models.CharField(db_column="id_distrit", max_length=16, null=True),
                ),
                (
                    "neighborhood_id",
                    models.CharField(db_column="id_bairro", max_length=16, null=True),
                ),
                (
                    "neighborhood_name",
                    models.CharField(db_column="nm_bairro", max_length=128, null=True),
                ),
            ],
            options={
                "db_table": '"Municipio"."Notificacao"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "municipality_geocode",
                        "cid10_code",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "municipality_geocode",
                    models.IntegerField(db_column="municipio_geocodigo"),
                ),
                ("cid10_code", models.CharField(db_column="cid10", max_length=16)),
                (
                    "baseline_variation",
                    models.FloatField(db_column="varcli", null=True),
                ),
                (
                    "baseline_critical",
                    models.FloatField(db_column="clicrit", null=True),
                ),
                (
                    "secondary_variation",
                    models.FloatField(db_column="varcli2", null=True),
                ),
                (
                    "secondary_critical",
                    models.FloatField(db_column="clicrit2", null=True),
                ),
                (
                    "preseason_threshold",
                    models.FloatField(db_column="limiar_preseason", null=True),
                ),
                (
                    "postseason_threshold",
                    models.FloatField(db_column="limiar_posseason", null=True),
                ),
                (
                    "epidemic_threshold",
                    models.FloatField(db_column="limiar_epidemico", null=True),
                ),
            ],
            options={
                "db_table": '"Dengue_global"."parameters"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Regional",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="nome", max_length=128)),
            ],
            options={
                "db_table": '"Dengue_global"."regional"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "geocode",
                    models.IntegerField(
                        db_column="geocodigo", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="nome", max_length=128)),
                ("abbreviation", models.CharField(db_column="uf", max_length=2)),
            ],
            options={
                "db_table": '"Dengue_global"."estado"',
                "managed": False,
            },
        ),
    ]
