# Generated by Django 5.2.11 on 2026-07-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados", "0006_episcannersirparams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episcannersirparams",
            name="geocode",
            field=models.ForeignKey(
                db_column="geocode",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dados.city",
            ),
        ),
    ]
