# Generated by Django 5.2.11 on 2026-07-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados", "0007_episcannersirparams_fk_geocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="episcannersirparams",
            name="t_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episcannersirparams",
            name="t_ini",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
