# Generated by Django 5.2.11 on 2026-07-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dados", "0008_episcannersirparams_add_t_fields"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="episcannersirparams",
            table='"episcanner"."sir_params"',
        ),
    ]
