# Generated by Django 3.2.25 on 2024-04-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinan',
            name='status_error',
            field=models.TextField(help_text='If Status ERROR, the traceback will be stored in status_error', null=True),
        ),
    ]
