# Generated by Django 3.2.25 on 2024-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_sinan_inserted_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinan',
            name='status',
            field=models.TextField(choices=[('waiting_chunk', 'Aguardando chunk'), ('chunking', 'Processando chunks'), ('waiting_insert', 'Aguardando inserção'), ('inserting', 'Inserindo dados'), ('error', 'Erro'), ('finished', 'Finalizado'), ('finished_misparsed', 'Finalizado com erro')], help_text='Upload status of the file'),
        ),
    ]
