# Generated by Django 3.2.25 on 2024-04-30 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_alter_sinan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sinan",
            name="uploaded_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
