# Generated by Django 3.2.25 on 2024-04-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_sinan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinan',
            name='misparsed_cols',
            field=models.JSONField(default=list, help_text='Name of the columns containing misparsed rows'),
        ),
    ]
