# Generated by Django 3.2.25 on 2024-12-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_sinanupload_inserted_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinanupload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
