# Generated by Django 3.2.25 on 2024-12-10 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0007_alter_sinanupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinanupload',
            name='inserted_rows',
        ),
        migrations.AlterField(
            model_name='sinanchunkedupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sinan_chunks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sinanuploadhistory',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='upload.sinanupload'),
        ),
    ]
