# Generated by Django 3.2.25 on 2024-12-27 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0010_auto_20241227_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinanchunkedupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
