# Generated by Django 3.2.25 on 2024-12-27 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_alter_sinanchunkedupload_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SINANUploadLogStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Error')], default=0)),
                ('log_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='sinanupload',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='upload.sinanuploadlogstatus'),
        ),
    ]
