# Generated by Django 3.2.25 on 2024-12-30 14:20

import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0012_auto_20241227_2250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sinanuploadlogstatus",
            name="log_file",
            field=models.FilePathField(
                path=upload.models.sinan_upload_log_path
            ),
        ),
    ]
