# Generated by Django 3.2.25 on 2025-01-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20250103_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinanuploadlogstatus',
            name='filtered_out',
        ),
    ]
