# Generated by Django 3.2.25 on 2025-01-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_remove_sinanuploadlogstatus_filtered_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinanuploadlogstatus',
            name='end_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sinanuploadlogstatus',
            name='start_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='SINANUploadHistory',
        ),
    ]
