# Generated by Django 3.2.25 on 2025-05-15 19:19

import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0019_sinanupload_date_formats"),
    ]

    operations = [
        migrations.AddField(
            model_name="sinanuploadlogstatus",
            name="residues_file",
            field=models.FilePathField(
                null=True, path=upload.models.sinan_upload_log_path
            ),
        ),
    ]
