# Generated by Django 3.2.25 on 2025-05-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0020_sinanuploadlogstatus_residues_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinanupload',
            name='date_formats',
            field=models.JSONField(default=dict, help_text="A dict with {'DT_COLUMN': 'date format'}"),
        ),
    ]
