# Generated by Django 3.2.25 on 2025-05-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0021_alter_sinanupload_date_formats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinanuploadlogstatus',
            name='residues_file',
        ),
    ]
