# Generated by Django 3.2.25 on 2025-05-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0022_remove_sinanuploadlogstatus_residues_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sinanuploadlogstatus",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Success"),
                    (1.1, "Success with residues"),
                    (2, "Error"),
                ],
                default=0,
            ),
        ),
    ]
