# Generated by Django 5.2.11 on 2026-06-26

from django.db import migrations


class Migration(migrations.Migration):
    """Remove database tables owned by the retired upload app."""

    dependencies = [
        ("upload", "0024_alter_sinanuploadlogstatus_status"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE public.upload_sinanupload;",
                    reverse_sql=None,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE public.upload_sinanchunkedupload;",
                    reverse_sql=None,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE public.upload_sinanuploadlogstatus;",
                    reverse_sql=None,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="SINANUpload",
                ),
                migrations.DeleteModel(
                    name="SINANChunkedUpload",
                ),
                migrations.DeleteModel(
                    name="SINANUploadLogStatus",
                ),
            ],
        ),
    ]
