# Generated by Django 3.2.25 on 2025-02-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlerta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_iniSE', models.DateField()),
                ('SE', models.IntegerField()),
                ('casos_est', models.FloatField(blank=True, null=True)),
                ('casos_est_min', models.IntegerField(blank=True, null=True)),
                ('casos_est_max', models.IntegerField(blank=True, null=True)),
                ('casos', models.IntegerField(blank=True, null=True)),
                ('municipio_geocodigo', models.IntegerField()),
                ('p_rt1', models.FloatField(blank=True, null=True)),
                ('p_inc100k', models.FloatField(blank=True, null=True)),
                ('Localidade_id', models.IntegerField(blank=True, null=True)),
                ('nivel', models.SmallIntegerField(blank=True, null=True)),
                ('versao_modelo', models.CharField(blank=True, max_length=40, null=True)),
                ('municipio_nome', models.CharField(blank=True, max_length=128, null=True)),
                ('tweet', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('Rt', models.FloatField(blank=True, null=True)),
                ('pop', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('tempmin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('umidmax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receptivo', models.SmallIntegerField(blank=True, null=True)),
                ('transmissao', models.SmallIntegerField(blank=True, null=True)),
                ('nivel_inc', models.SmallIntegerField(blank=True, null=True)),
                ('umidmed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('umidmin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tempmed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tempmax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('casprov', models.IntegerField(blank=True, null=True)),
                ('casprov_est', models.FloatField(blank=True, null=True)),
                ('casprov_est_min', models.IntegerField(blank=True, null=True)),
                ('casprov_est_max', models.IntegerField(blank=True, null=True)),
                ('casconf', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"Municipio"."Historico_alerta"',
            },
        ),
        migrations.AddIndex(
            model_name='historicoalerta',
            index=models.Index(fields=['data_iniSE'], name='Alerta_idx_data'),
        ),
        migrations.AddConstraint(
            model_name='historicoalerta',
            constraint=models.UniqueConstraint(fields=('SE', 'municipio_geocodigo', 'Localidade_id'), name='alertas_unicos'),
        ),
    ]
