# Generated by Django 3.2.25 on 2025-02-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250219_1336'),
    ]

    operations = [
        migrations.RunSQL(
            """
            GRANT ALL ON TABLE "Municipio"."Historico_alerta" TO "Dengue";
            GRANT ALL ON TABLE "Municipio"."Historico_alerta" TO dengue;
            GRANT SELECT ON TABLE "Municipio"."Historico_alerta" TO infodenguedev;
            """
        ),
        migrations.RunSQL(
            """
            GRANT ALL ON TABLE "Municipio"."Historico_alerta_chik" TO "Dengue";
            GRANT ALL ON TABLE "Municipio"."Historico_alerta_chik" TO dengue;
            GRANT SELECT ON TABLE "Municipio"."Historico_alerta_chik" TO infodenguedev;
            """
        ),
        migrations.RunSQL(
            """
            GRANT ALL ON TABLE "Municipio"."Historico_alerta_zika" TO "Dengue";
            GRANT ALL ON TABLE "Municipio"."Historico_alerta_zika" TO dengue;
            GRANT SELECT ON TABLE "Municipio"."Historico_alerta_zika" TO infodenguedev;
            """
        ),
    ]
