# Generated by Django 3.2.25 on 2025-02-19 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extensions_and_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('bairro_id', models.IntegerField()),
            ],
            options={
                'db_table': '"Municipio"."Bairro"',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('geocodigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=128)),
                ('geojson', models.TextField()),
                ('regiao', models.CharField(max_length=32)),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'db_table': '"Dengue_global"."estado"',
            },
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('nome', models.CharField(max_length=32)),
                ('populacao', models.IntegerField()),
                ('geojson', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('municipio_geocodigo', models.IntegerField()),
                ('codigo_estacao_wu', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': '"Municipio"."Localidade"',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('municipio_geocodigo', models.IntegerField(primary_key=True, serialize=False)),
                ('limiar_preseason', models.FloatField(blank=True, null=True)),
                ('limiar_posseason', models.FloatField(blank=True, null=True)),
                ('limiar_epidemico', models.FloatField(blank=True, null=True)),
                ('varcli', models.TextField(blank=True, null=True)),
                ('clicrit', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cid10', models.CharField(blank=True, max_length=255, null=True)),
                ('codmodelo', models.CharField(blank=True, max_length=255, null=True)),
                ('varcli2', models.CharField(blank=True, max_length=16, null=True)),
                ('clicrit2', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('codigo_estacao_wu', models.CharField(blank=True, max_length=255, null=True)),
                ('estacao_wu_sec', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"Dengue_global"."parameters"',
            },
        ),
        migrations.AddIndex(
            model_name='parameters',
            index=models.Index(fields=['municipio_geocodigo'], name='parameters_idx_gc'),
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['geocodigo'], name='estado_idx_gc'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='localidade',
            field=models.ForeignKey(db_column='Localidade_id', on_delete=django.db.models.deletion.CASCADE, to='core.localidade'),
        ),
        migrations.AddConstraint(
            model_name='bairro',
            constraint=models.UniqueConstraint(fields=('nome', 'bairro_id'), name='Bairro_pk'),
        ),
        migrations.AlterUniqueTogether(
            name='bairro',
            unique_together={('nome', 'bairro_id')},
        ),
    ]
