# Generated by Django 3.2.25 on 2025-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250219_2154'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bairro',
            name='Bairro_pk',
        ),
        migrations.AlterField(
            model_name='bairro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='bairro',
            unique_together=set(),
        ),
    ]
