# Generated by Django 3.2.25 on 2025-02-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250220_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaCemaden',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('sensor', models.CharField(max_length=32)),
                ('datahora', models.DateTimeField()),
                ('estacao_cemaden_codestacao', models.CharField(db_column='Estacao_cemaden_codestacao', max_length=10)),
            ],
            options={
                'db_table': '"Municipio"."Clima_cemaden"',
            },
        ),
        migrations.AddIndex(
            model_name='climacemaden',
            index=models.Index(fields=['-datahora'], name='chuva_idx_data'),
        ),
        migrations.AddIndex(
            model_name='climacemaden',
            index=models.Index(fields=['estacao_cemaden_codestacao'], name='estacoes_idx'),
        ),
    ]
