# Generated by Django 3.2.25 on 2025-02-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250220_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaWU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('temp_med', models.FloatField(blank=True, null=True)),
                ('data_dia', models.DateField()),
                ('umid_min', models.FloatField(blank=True, null=True)),
                ('umid_med', models.FloatField(blank=True, null=True)),
                ('umid_max', models.FloatField(blank=True, null=True)),
                ('pressao_min', models.FloatField(blank=True, null=True)),
                ('pressao_med', models.FloatField(blank=True, null=True)),
                ('pressao_max', models.FloatField(blank=True, null=True)),
                ('estacao_wu_estacao_id', models.CharField(db_column='Estacao_wu_estacao_id', max_length=4)),
            ],
            options={
                'db_table': '"Municipio"."Clima_wu"',
            },
        ),
        migrations.AddIndex(
            model_name='climawu',
            index=models.Index(fields=['-data_dia'], name='WU_idx_data'),
        ),
    ]
