# Generated by Django 3.2.25 on 2025-02-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250220_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoCemaden',
            fields=[
                ('codestacao', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=128)),
                ('municipio', models.CharField(blank=True, max_length=128, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': '"Municipio"."Estacao_cemaden"',
            },
        ),
    ]
