# Generated by Django 3.2.25 on 2025-02-20 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_estacaocemaden'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoWU',
            fields=[
                ('estacao_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nome', models.CharField(max_length=128)),
                ('localidades', models.ForeignKey(blank=True, db_column='Localidades_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localidade')),
            ],
            options={
                'db_table': '"Municipio"."Estacao_wu"',
            },
        ),
    ]
