# Generated by Django 3.2.25 on 2025-02-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_estacaowu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dt_notific', models.DateField(blank=True, null=True)),
                ('se_notif', models.IntegerField(blank=True, null=True)),
                ('ano_notif', models.IntegerField(blank=True, null=True)),
                ('dt_sin_pri', models.DateField(blank=True, null=True)),
                ('se_sin_pri', models.IntegerField(blank=True, null=True)),
                ('dt_digita', models.DateField(blank=True, null=True)),
                ('municipio_geocodigo', models.IntegerField(blank=True, null=True)),
                ('nu_notific', models.IntegerField(blank=True, null=True)),
                ('cid10_codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('dt_nasc', models.DateField(blank=True, null=True)),
                ('cs_sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('nu_idade_n', models.IntegerField(blank=True, null=True)),
                ('resul_pcr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criterio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('classi_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dt_chik_s1', models.DateField(blank=True, null=True)),
                ('dt_chik_s2', models.DateField(blank=True, null=True)),
                ('dt_prnt', models.DateField(blank=True, null=True)),
                ('res_chiks1', models.CharField(blank=True, max_length=255, null=True)),
                ('res_chiks2', models.CharField(blank=True, max_length=255, null=True)),
                ('resul_prnt', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_soro', models.DateField(blank=True, null=True)),
                ('resul_soro', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_ns1', models.DateField(blank=True, null=True)),
                ('resul_ns1', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_viral', models.DateField(blank=True, null=True)),
                ('resul_vi_n', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_pcr', models.DateField(blank=True, null=True)),
                ('sorotipo', models.CharField(blank=True, max_length=255, null=True)),
                ('id_distrit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_bairro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nm_bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('id_unidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': '"Municipio"."Notificacao"',
            },
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['-dt_notific', '-se_notif'], name='Dengue_idx_data'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['cid10_codigo'], name='notificacao_cid10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificacao',
            unique_together={('nu_notific', 'dt_notific', 'cid10_codigo', 'municipio_geocodigo')},
        ),
    ]
