# Generated by Django 3.2.25 on 2025-02-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20250221_0008'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP VIEW IF EXISTS "Municipio".historico_casos;
            CREATE VIEW "Municipio".historico_casos AS
            SELECT
                ROW_NUMBER() OVER () AS id,
                dengue."data_iniSE",
                dengue."SE",
                (COALESCE(dengue.casos_est, (0.0)::real) + COALESCE(chik.casos_est, (0.0)::real)) AS casos_est,
                (COALESCE(dengue.casos_est_min, 0) + COALESCE(chik.casos_est_min, 0)) AS casos_est_min,
                (COALESCE(dengue.casos_est_max, 0) + COALESCE(chik.casos_est_max, 0)) AS casos_est_max,
                (COALESCE(dengue.casos, 0) + COALESCE(chik.casos, 0)) AS casos,
                dengue.municipio_geocodigo
            FROM ("Municipio"."Historico_alerta" dengue
                FULL JOIN "Municipio"."Historico_alerta_chik" chik ON (((dengue."SE" = chik."SE") AND (dengue.municipio_geocodigo = chik.municipio_geocodigo))));
        """),
    ]
