# Generated by Django 3.2.25 on 2025-02-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notificacaoview'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iniSE', models.DateField()),
                ('SE', models.IntegerField()),
                ('casos_est', models.FloatField()),
                ('casos_est_min', models.IntegerField()),
                ('casos_est_max', models.IntegerField()),
                ('casos', models.IntegerField()),
                ('municipio_geocodigo', models.IntegerField()),
            ],
            options={
                'db_table': '"Municipio"."historico_casos"',
                'managed': False,
            },
        ),
    ]
