# Generated by Django 3.2.25 on 2025-02-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notificacaoview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificacaoview',
            table='Municipio"."historico_casos',
        ),
    ]
