# Generated by Django 3.2.25 on 2025-02-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notificacaoview_table'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE SCHEMA IF NOT EXISTS weather;
        """),
        migrations.CreateModel(
            name='CopernicusBra',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('geocode', models.TextField()),
                ('temp_max', models.FloatField()),
                ('precip_max', models.FloatField()),
                ('umid_max', models.FloatField()),
                ('pressao_max', models.FloatField()),
                ('temp_med', models.FloatField()),
                ('precip_med', models.FloatField()),
                ('umid_med', models.FloatField()),
                ('pressao_med', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('precip_min', models.FloatField()),
                ('umid_min', models.FloatField()),
                ('pressao_min', models.FloatField()),
                ('precip_tot', models.FloatField()),
                ('epiweek', models.TextField()),
            ],
            options={
                'db_table': '"weather"."copernicus_bra"',
            },
        ),
        migrations.AddConstraint(
            model_name='copernicusbra',
            constraint=models.UniqueConstraint(
                fields=('date', 'geocode'), name='composite_primary_key'),
        ),
        migrations.AlterUniqueTogether(
            name='copernicusbra',
            unique_together={('date', 'geocode')},
        ),
    ]
