# Generated by Django 3.2.25 on 2025-02-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20250221_1745'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP MATERIALIZED VIEW IF EXISTS hist_uf_chik_materialized_view;
            CREATE MATERIALIZED VIEW public.hist_uf_chik_materialized_view AS
            SELECT upper((state.uf)::text) AS state_abbv,
                city.uf AS state_name,
                alerta.municipio_geocodigo,
                alerta."SE",
                alerta."data_iniSE",
                alerta.casos_est,
                alerta.casos,
                alerta.nivel,
                alerta.receptivo
            FROM (("Municipio"."Historico_alerta_chik" alerta
                JOIN "Dengue_global"."Municipio" city ON ((alerta.municipio_geocodigo = city.geocodigo)))
                JOIN "Dengue_global".estado state ON ((upper((city.uf)::text) = (state.nome)::text)))
            WHERE (alerta."data_iniSE" >= ( SELECT (max(alerta_1."data_iniSE") - '28 days'::interval) AS max_date
                    FROM "Municipio"."Historico_alerta_chik" alerta_1))
            ORDER BY alerta."data_iniSE"
            WITH NO DATA;
            ALTER TABLE public.hist_uf_chik_materialized_view OWNER TO dengueadmin;
        """),
        migrations.RunSQL("""
            DROP MATERIALIZED VIEW IF EXISTS hist_uf_dengue_materialized_view;
            CREATE MATERIALIZED VIEW public.hist_uf_dengue_materialized_view AS
            SELECT upper((state.uf)::text) AS state_abbv,
                city.uf AS state_name,
                alerta.municipio_geocodigo,
                alerta."SE",
                alerta."data_iniSE",
                alerta.casos_est,
                alerta.casos,
                alerta.nivel,
                alerta.receptivo
            FROM (("Municipio"."Historico_alerta" alerta
                JOIN "Dengue_global"."Municipio" city ON ((alerta.municipio_geocodigo = city.geocodigo)))
                JOIN "Dengue_global".estado state ON ((upper((city.uf)::text) = (state.nome)::text)))
            WHERE (alerta."data_iniSE" >= ( SELECT (max(alerta_1."data_iniSE") - '28 days'::interval) AS max_date
                    FROM "Municipio"."Historico_alerta" alerta_1))
            ORDER BY alerta."data_iniSE"
            WITH NO DATA;
            ALTER TABLE public.hist_uf_dengue_materialized_view OWNER TO dengueadmin;
        """),
        migrations.RunSQL("""
            DROP MATERIALIZED VIEW IF EXISTS hist_uf_zika_materialized_view;
            CREATE MATERIALIZED VIEW public.hist_uf_zika_materialized_view AS
            SELECT upper((state.uf)::text) AS state_abbv,
                city.uf AS state_name,
                alerta.municipio_geocodigo,
                alerta."SE",
                alerta."data_iniSE",
                alerta.casos_est,
                alerta.casos,
                alerta.nivel,
                alerta.receptivo
            FROM (("Municipio"."Historico_alerta_zika" alerta
                JOIN "Dengue_global"."Municipio" city ON ((alerta.municipio_geocodigo = city.geocodigo)))
                JOIN "Dengue_global".estado state ON ((upper((city.uf)::text) = (state.nome)::text)))
            WHERE (alerta."data_iniSE" >= ( SELECT (max(alerta_1."data_iniSE") - '28 days'::interval) AS max_date
                    FROM "Municipio"."Historico_alerta_zika" alerta_1))
            ORDER BY alerta."data_iniSE"
            WITH NO DATA;
            ALTER TABLE public.hist_uf_zika_materialized_view OWNER TO dengueadmin;
        """),
        migrations.RunSQL("""
            DROP MATERIALIZED VIEW IF EXISTS uf_total_chik_view;
            CREATE MATERIALIZED VIEW public.uf_total_chik_view AS
            SELECT "Municipio".uf,
                "Historico_alerta_chik"."data_iniSE" AS data,
                sum("Historico_alerta_chik".casos) AS casos_s,
                sum("Historico_alerta_chik".casos_est) AS casos_est_s
            FROM ("Municipio"."Historico_alerta_chik"
                JOIN "Dengue_global"."Municipio" ON (("Historico_alerta_chik".municipio_geocodigo = "Municipio".geocodigo)))
            GROUP BY "Historico_alerta_chik"."data_iniSE", "Municipio".uf
            ORDER BY "Municipio".uf, "Historico_alerta_chik"."data_iniSE"
            WITH NO DATA;
            ALTER TABLE public.uf_total_chik_view OWNER TO administrador;
        """),
        migrations.RunSQL("""
            DROP MATERIALIZED VIEW IF EXISTS uf_total_view;
            CREATE MATERIALIZED VIEW public.uf_total_view AS
            SELECT "Municipio".uf,
                "Historico_alerta"."data_iniSE" AS data,
                sum("Historico_alerta".casos) AS casos_s,
                sum("Historico_alerta".casos_est) AS casos_est_s
            FROM ("Municipio"."Historico_alerta"
                JOIN "Dengue_global"."Municipio" ON (("Historico_alerta".municipio_geocodigo = "Municipio".geocodigo)))
            GROUP BY "Historico_alerta"."data_iniSE", "Municipio".uf
            ORDER BY "Municipio".uf, "Historico_alerta"."data_iniSE"
            WITH NO DATA;
            ALTER TABLE public.uf_total_view OWNER TO administrador;
        """),
        migrations.RunSQL("""
            DROP MATERIALIZED VIEW IF EXISTS uf_total_zika_view;
            CREATE MATERIALIZED VIEW public.uf_total_zika_view AS
            SELECT "Municipio".uf,
                "Historico_alerta_zika"."data_iniSE" AS data,
                sum("Historico_alerta_zika".casos) AS casos_s,
                sum("Historico_alerta_zika".casos_est) AS casos_est_s
            FROM ("Municipio"."Historico_alerta_zika"
                JOIN "Dengue_global"."Municipio" ON (("Historico_alerta_zika".municipio_geocodigo = "Municipio".geocodigo)))
            GROUP BY "Historico_alerta_zika"."data_iniSE", "Municipio".uf
            ORDER BY "Municipio".uf, "Historico_alerta_zika"."data_iniSE"
            WITH NO DATA;
            ALTER TABLE public.uf_total_zika_view OWNER TO postgres;
        """),
        migrations.RunSQL("""
            REFRESH MATERIALIZED VIEW uf_total_zika_view;
            REFRESH MATERIALIZED VIEW uf_total_chik_view;
            REFRESH MATERIALIZED VIEW uf_total_view;
            REFRESH MATERIALIZED VIEW hist_uf_dengue_materialized_view;
            REFRESH MATERIALIZED VIEW hist_uf_chik_materialized_view;
            REFRESH MATERIALIZED VIEW hist_uf_zika_materialized_view;
        """),
    ]
