# Generated by Django 5.2.11 on 2026-03-02 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="delivery_week",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(53),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="delivery_year",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="size_bytes",
            field=models.BigIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
