# Generated by Django 5.2.11 on 2026-03-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ingestion",
            "0002_alter_run_delivery_week_alter_run_delivery_year_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="rows_duplicate",
            field=models.BigIntegerField(default=0),
        ),
    ]
