# Generated by Django 5.2.11 on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ingestion", "0003_run_rows_duplicate")]

    operations = [
        migrations.AddIndex(
            model_name="sinanstage",
            index=models.Index(
                fields=[
                    "run",
                    "nu_notific",
                    "dt_notific",
                    "cid10_codigo",
                    "municipio_geocodigo",
                ],
                name="ix_ing_stage_rollback_keys",
            ),
        ),
        migrations.CreateModel(
            name="RunRollback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                             serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"),
                 ("completed", "Completed"), ("failed", "Failed")],
                 default="pending", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("rows_new_only", models.BigIntegerField(default=0)),
                ("rows_old_only", models.BigIntegerField(default=0)),
                ("rows_changed", models.BigIntegerField(default=0)),
                ("rows_unchanged", models.BigIntegerField(default=0)),
                ("rows_deleted", models.BigIntegerField(default=0)),
                ("rows_restored", models.BigIntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                ("errors", models.JSONField(default=list)),
                ("current_run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name="rollbacks_started", to="ingestion.run")),
                ("restore_run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name="rollbacks_restored", to="ingestion.run")),
            ],
            options={"db_table": '"ingestion"."run_rollback"'},
        ),
        migrations.AddIndex(
            model_name="runrollback",
            index=models.Index(fields=["current_run", "status"],
                               name="ix_ing_rollback_current_status"),
        ),
        migrations.AddConstraint(
            model_name="runrollback",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "completed")),
                fields=("current_run",),
                name="ux_ing_rollback_completed_run",
            ),
        ),
    ]
